# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'CadEmpresa.ui'
##
## Created by: Qt User Interface Compiler version 6.7.3
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QBrush, QColor, QConicalGradient, QCursor,
    QFont, QFontDatabase, QGradient, QIcon,
    QImage, QKeySequence, QLinearGradient, QPainter,
    QPalette, QPixmap, QRadialGradient, QTransform)
from PySide6.QtWidgets import (QApplication, QDateEdit, QLCDNumber, QLabel,
    QLineEdit, QMainWindow, QMenuBar, QPushButton,
    QSizePolicy, QStatusBar, QTabWidget, QWidget)

class Ui_CadEmpresa(object):
    def setupUi(self, CadEmpresa):
        if not CadEmpresa.objectName():
            CadEmpresa.setObjectName(u"CadEmpresa")
        CadEmpresa.resize(680, 480)
        CadEmpresa.setMinimumSize(QSize(680, 480))
        CadEmpresa.setMaximumSize(QSize(680, 480))
        self.centralwidget = QWidget(CadEmpresa)
        self.centralwidget.setObjectName(u"centralwidget")
        self.tabWidget = QTabWidget(self.centralwidget)
        self.tabWidget.setObjectName(u"tabWidget")
        self.tabWidget.setGeometry(QRect(0, 0, 680, 480))
        font = QFont()
        font.setStyleStrategy(QFont.PreferAntialias)
        self.tabWidget.setFont(font)
#if QT_CONFIG(tooltip)
        self.tabWidget.setToolTip(u"")
#endif // QT_CONFIG(tooltip)
        self.DdPrincipais = QWidget()
        self.DdPrincipais.setObjectName(u"DdPrincipais")
        self.txt_razao_social = QLineEdit(self.DdPrincipais)
        self.txt_razao_social.setObjectName(u"txt_razao_social")
        self.txt_razao_social.setGeometry(QRect(10, 50, 521, 21))
        font1 = QFont()
        font1.setFamilies([u"Segoe UI"])
        font1.setPointSize(12)
        font1.setStyleStrategy(QFont.NoAntialias)
        self.txt_razao_social.setFont(font1)
        self.label = QLabel(self.DdPrincipais)
        self.label.setObjectName(u"label")
        self.label.setGeometry(QRect(10, 30, 91, 16))
        font2 = QFont()
        font2.setFamilies([u"Segoe UI"])
        font2.setPointSize(12)
        self.label.setFont(font2)
        self.txt_nome_fantasia = QLineEdit(self.DdPrincipais)
        self.txt_nome_fantasia.setObjectName(u"txt_nome_fantasia")
        self.txt_nome_fantasia.setGeometry(QRect(10, 100, 521, 21))
        self.txt_nome_fantasia.setFont(font2)
        self.label_3 = QLabel(self.DdPrincipais)
        self.label_3.setObjectName(u"label_3")
        self.label_3.setGeometry(QRect(10, 80, 121, 16))
        self.label_3.setFont(font2)
        self.txt_cnpj = QLineEdit(self.DdPrincipais)
        self.txt_cnpj.setObjectName(u"txt_cnpj")
        self.txt_cnpj.setGeometry(QRect(10, 150, 251, 21))
        self.txt_cnpj.setFont(font2)
        self.label_4 = QLabel(self.DdPrincipais)
        self.label_4.setObjectName(u"label_4")
        self.label_4.setGeometry(QRect(10, 130, 91, 16))
        self.label_4.setFont(font2)
        self.label_5 = QLabel(self.DdPrincipais)
        self.label_5.setObjectName(u"label_5")
        self.label_5.setGeometry(QRect(280, 130, 121, 16))
        self.label_5.setFont(font2)
        self.date_abertura = QDateEdit(self.DdPrincipais)
        self.date_abertura.setObjectName(u"date_abertura")
        self.date_abertura.setGeometry(QRect(280, 150, 131, 22))
        self.date_abertura.setCalendarPopup(True)
        self.btn_salvar = QPushButton(self.DdPrincipais)
        self.btn_salvar.setObjectName(u"btn_salvar")
        self.btn_salvar.setEnabled(False)
        self.btn_salvar.setGeometry(QRect(380, 360, 140, 48))
        font3 = QFont()
        font3.setFamilies([u"Segoe UI"])
        font3.setPointSize(12)
        font3.setBold(True)
        font3.setItalic(False)
        font3.setUnderline(False)
        self.btn_salvar.setFont(font3)
        self.bt_cancelar = QPushButton(self.DdPrincipais)
        self.bt_cancelar.setObjectName(u"bt_cancelar")
        self.bt_cancelar.setEnabled(True)
        self.bt_cancelar.setGeometry(QRect(530, 360, 140, 48))
        self.bt_cancelar.setFont(font3)
#if QT_CONFIG(tooltip)
        self.bt_cancelar.setToolTip(u"")
#endif // QT_CONFIG(tooltip)
        self.btn_alterar = QPushButton(self.DdPrincipais)
        self.btn_alterar.setObjectName(u"btn_alterar")
        self.btn_alterar.setGeometry(QRect(20, 360, 140, 48))
        self.btn_alterar.setFont(font3)
        self.btn_alterar.setToolTipDuration(5)
        self.lcd_id = QLCDNumber(self.DdPrincipais)
        self.lcd_id.setObjectName(u"lcd_id")
        self.lcd_id.setGeometry(QRect(10, 0, 61, 23))
        self.lcd_id.setProperty(u"intValue", 0)
        self.tabWidget.addTab(self.DdPrincipais, "")
        self.DdAdicionais = QWidget()
        self.DdAdicionais.setObjectName(u"DdAdicionais")
        self.tabWidget.addTab(self.DdAdicionais, "")
        CadEmpresa.setCentralWidget(self.centralwidget)
        self.menubar = QMenuBar(CadEmpresa)
        self.menubar.setObjectName(u"menubar")
        self.menubar.setGeometry(QRect(0, 0, 680, 21))
        CadEmpresa.setMenuBar(self.menubar)
        self.statusbar = QStatusBar(CadEmpresa)
        self.statusbar.setObjectName(u"statusbar")
        CadEmpresa.setStatusBar(self.statusbar)

        self.retranslateUi(CadEmpresa)

        self.tabWidget.setCurrentIndex(0)


        QMetaObject.connectSlotsByName(CadEmpresa)
    # setupUi

    def retranslateUi(self, CadEmpresa):
        CadEmpresa.setWindowTitle(QCoreApplication.translate("CadEmpresa", u"Cadastro da Empresa", None))
        self.label.setText(QCoreApplication.translate("CadEmpresa", u"Raz\u00e3o Social:", None))
        self.txt_nome_fantasia.setText("")
        self.label_3.setText(QCoreApplication.translate("CadEmpresa", u"Nome Fantasia:", None))
        self.label_4.setText(QCoreApplication.translate("CadEmpresa", u"CNPJ/CPF:", None))
        self.label_5.setText(QCoreApplication.translate("CadEmpresa", u"Data de Abertura:", None))
        self.btn_salvar.setText(QCoreApplication.translate("CadEmpresa", u"&Salvar", None))
#if QT_CONFIG(shortcut)
        self.btn_salvar.setShortcut(QCoreApplication.translate("CadEmpresa", u"Alt+S", None))
#endif // QT_CONFIG(shortcut)
        self.bt_cancelar.setText(QCoreApplication.translate("CadEmpresa", u"&Cancelar", None))
#if QT_CONFIG(shortcut)
        self.bt_cancelar.setShortcut(QCoreApplication.translate("CadEmpresa", u"Alt+C", None))
#endif // QT_CONFIG(shortcut)
#if QT_CONFIG(tooltip)
        self.btn_alterar.setToolTip("")
#endif // QT_CONFIG(tooltip)
        self.btn_alterar.setText(QCoreApplication.translate("CadEmpresa", u"&Alterar", None))
#if QT_CONFIG(shortcut)
        self.btn_alterar.setShortcut(QCoreApplication.translate("CadEmpresa", u"Ctrl+A", None))
#endif // QT_CONFIG(shortcut)
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.DdPrincipais), QCoreApplication.translate("CadEmpresa", u"Dados Principais", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.DdAdicionais), QCoreApplication.translate("CadEmpresa", u"Dados Adicionais", None))
    # retranslateUi

