from ui_display_field import DisplayAssociateTable
from ui.MainLogin import Ui_Login
from ui.MainWindow import Ui_MainWindow
from ui.CadEmpresa import Ui_CadEmpresa
from ui.CadFornecedor import Ui_CadFornecedor
from ui.dialogMensagem import Ui_InfMensagem
from ui.CadRamoAtividade import Ui_dialogRamoAtividade
from ui.CadUser import  Ui_CadUser
from ui.FrmGraficFinc import Ui_frm_dashboard
from ui.CadEntregas import Ui_CadEntregas
from ui.BootingSystem import Ui_booting_system
from ui.CadProdutos import Ui_CadProduto