# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'CadAgencia.ui'
##
## Created by: Qt User Interface Compiler version 6.7.3
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QBrush, QColor, QConicalGradient, QCursor,
    QFont, QFontDatabase, QGradient, QIcon,
    QImage, QKeySequence, QLinearGradient, QPainter,
    QPalette, QPixmap, QRadialGradient, QTransform)
from PySide6.QtWidgets import (QApplication, QCheckBox, QComboBox, QDialog,
    QLCDNumber, QLabel, QLineEdit, QPlainTextEdit,
    QPushButton, QSizePolicy, QTabWidget, QWidget)

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        if not Dialog.objectName():
            Dialog.setObjectName(u"Dialog")
        Dialog.setWindowModality(Qt.ApplicationModal)
        Dialog.resize(731, 454)
        Dialog.setStyleSheet(u"font: 12pt \"Segoe UI\";")
        self.tabWidget = QTabWidget(Dialog)
        self.tabWidget.setObjectName(u"tabWidget")
        self.tabWidget.setGeometry(QRect(0, 0, 731, 401))
        self.tabWidget.setStyleSheet(u"font: 12pt \"Segoe UI\";")
        self.DdPrincipal = QWidget()
        self.DdPrincipal.setObjectName(u"DdPrincipal")
        self.label_2 = QLabel(self.DdPrincipal)
        self.label_2.setObjectName(u"label_2")
        self.label_2.setGeometry(QRect(20, 150, 141, 21))
        self.lcdNumber = QLCDNumber(self.DdPrincipal)
        self.lcdNumber.setObjectName(u"lcdNumber")
        self.lcdNumber.setGeometry(QRect(20, 0, 81, 23))
        self.lineEdit_3 = QLineEdit(self.DdPrincipal)
        self.lineEdit_3.setObjectName(u"lineEdit_3")
        self.lineEdit_3.setGeometry(QRect(170, 120, 61, 21))
        self.label_4 = QLabel(self.DdPrincipal)
        self.label_4.setObjectName(u"label_4")
        self.label_4.setGeometry(QRect(160, 30, 141, 21))
        self.lineEdit_2 = QLineEdit(self.DdPrincipal)
        self.lineEdit_2.setObjectName(u"lineEdit_2")
        self.lineEdit_2.setGeometry(QRect(20, 180, 241, 21))
        self.lineEdit_2.setCursorPosition(18)
        self.comboBox = QComboBox(self.DdPrincipal)
        self.comboBox.setObjectName(u"comboBox")
        self.comboBox.setGeometry(QRect(160, 60, 321, 22))
        self.lineEdit_4 = QLineEdit(self.DdPrincipal)
        self.lineEdit_4.setObjectName(u"lineEdit_4")
        self.lineEdit_4.setGeometry(QRect(20, 60, 131, 21))
        self.checkBox = QCheckBox(self.DdPrincipal)
        self.checkBox.setObjectName(u"checkBox")
        self.checkBox.setGeometry(QRect(560, 0, 101, 31))
        self.checkBox.setChecked(True)
        self.label = QLabel(self.DdPrincipal)
        self.label.setObjectName(u"label")
        self.label.setGeometry(QRect(20, 90, 141, 21))
        self.lineEdit = QLineEdit(self.DdPrincipal)
        self.lineEdit.setObjectName(u"lineEdit")
        self.lineEdit.setGeometry(QRect(20, 120, 131, 21))
        self.label_3 = QLabel(self.DdPrincipal)
        self.label_3.setObjectName(u"label_3")
        self.label_3.setGeometry(QRect(20, 30, 141, 21))
        self.pushButton = QPushButton(self.DdPrincipal)
        self.pushButton.setObjectName(u"pushButton")
        self.pushButton.setGeometry(QRect(490, 60, 25, 25))
        self.label_5 = QLabel(self.DdPrincipal)
        self.label_5.setObjectName(u"label_5")
        self.label_5.setGeometry(QRect(140, 120, 47, 13))
        font = QFont()
        font.setFamilies([u"MS Shell Dlg 2"])
        font.setPointSize(28)
        font.setBold(False)
        font.setItalic(False)
        self.label_5.setFont(font)
        self.label_5.setStyleSheet(u"font: 28pt \"MS Shell Dlg 2\";")
        self.tabWidget.addTab(self.DdPrincipal, "")
        self.DdAdicionais = QWidget()
        self.DdAdicionais.setObjectName(u"DdAdicionais")
        self.label_11 = QLabel(self.DdAdicionais)
        self.label_11.setObjectName(u"label_11")
        self.label_11.setGeometry(QRect(10, 10, 141, 21))
        self.lineEdit_9 = QLineEdit(self.DdAdicionais)
        self.lineEdit_9.setObjectName(u"lineEdit_9")
        self.lineEdit_9.setGeometry(QRect(10, 30, 501, 21))
        self.label_18 = QLabel(self.DdAdicionais)
        self.label_18.setObjectName(u"label_18")
        self.label_18.setGeometry(QRect(520, 10, 141, 21))
        self.lineEdit_16 = QLineEdit(self.DdAdicionais)
        self.lineEdit_16.setObjectName(u"lineEdit_16")
        self.lineEdit_16.setGeometry(QRect(520, 30, 121, 21))
        self.label_19 = QLabel(self.DdAdicionais)
        self.label_19.setObjectName(u"label_19")
        self.label_19.setGeometry(QRect(10, 50, 141, 21))
        self.lineEdit_15 = QLineEdit(self.DdAdicionais)
        self.lineEdit_15.setObjectName(u"lineEdit_15")
        self.lineEdit_15.setGeometry(QRect(10, 70, 291, 21))
        self.label_20 = QLabel(self.DdAdicionais)
        self.label_20.setObjectName(u"label_20")
        self.label_20.setGeometry(QRect(320, 50, 211, 21))
        self.lineEdit_17 = QLineEdit(self.DdAdicionais)
        self.lineEdit_17.setObjectName(u"lineEdit_17")
        self.lineEdit_17.setGeometry(QRect(320, 70, 321, 21))
        self.label_21 = QLabel(self.DdAdicionais)
        self.label_21.setObjectName(u"label_21")
        self.label_21.setGeometry(QRect(10, 100, 141, 21))
        self.lineEdit_18 = QLineEdit(self.DdAdicionais)
        self.lineEdit_18.setObjectName(u"lineEdit_18")
        self.lineEdit_18.setGeometry(QRect(10, 120, 161, 21))
        self.label_22 = QLabel(self.DdAdicionais)
        self.label_22.setObjectName(u"label_22")
        self.label_22.setGeometry(QRect(190, 100, 141, 21))
        self.lineEdit_19 = QLineEdit(self.DdAdicionais)
        self.lineEdit_19.setObjectName(u"lineEdit_19")
        self.lineEdit_19.setGeometry(QRect(190, 120, 291, 21))
        self.label_23 = QLabel(self.DdAdicionais)
        self.label_23.setObjectName(u"label_23")
        self.label_23.setGeometry(QRect(490, 100, 141, 21))
        self.lineEdit_20 = QLineEdit(self.DdAdicionais)
        self.lineEdit_20.setObjectName(u"lineEdit_20")
        self.lineEdit_20.setGeometry(QRect(490, 120, 151, 21))
        self.lineEdit_20.setInputMethodHints(Qt.ImhNoAutoUppercase)
        self.lineEdit_20.setMaxLength(2)
        self.label_24 = QLabel(self.DdAdicionais)
        self.label_24.setObjectName(u"label_24")
        self.label_24.setGeometry(QRect(10, 160, 131, 16))
        self.lineEdit_21 = QLineEdit(self.DdAdicionais)
        self.lineEdit_21.setObjectName(u"lineEdit_21")
        self.lineEdit_21.setGeometry(QRect(10, 180, 181, 21))
        self.lineEdit_21.setMaxLength(15)
        self.lineEdit_21.setCursorMoveStyle(Qt.VisualMoveStyle)
        self.lineEdit_22 = QLineEdit(self.DdAdicionais)
        self.lineEdit_22.setObjectName(u"lineEdit_22")
        self.lineEdit_22.setGeometry(QRect(460, 180, 181, 21))
        self.lineEdit_22.setMaxLength(14)
        self.lineEdit_22.setCursorMoveStyle(Qt.VisualMoveStyle)
        self.label_25 = QLabel(self.DdAdicionais)
        self.label_25.setObjectName(u"label_25")
        self.label_25.setGeometry(QRect(460, 160, 131, 16))
        self.checkBox_4 = QCheckBox(self.DdAdicionais)
        self.checkBox_4.setObjectName(u"checkBox_4")
        self.checkBox_4.setGeometry(QRect(210, 180, 151, 17))
        self.checkBox_4.setChecked(False)
        self.label_26 = QLabel(self.DdAdicionais)
        self.label_26.setObjectName(u"label_26")
        self.label_26.setGeometry(QRect(10, 210, 131, 16))
        self.lineEdit_23 = QLineEdit(self.DdAdicionais)
        self.lineEdit_23.setObjectName(u"lineEdit_23")
        self.lineEdit_23.setGeometry(QRect(10, 230, 351, 21))
        self.label_27 = QLabel(self.DdAdicionais)
        self.label_27.setObjectName(u"label_27")
        self.label_27.setGeometry(QRect(390, 210, 131, 16))
        self.plainTextEdit = QPlainTextEdit(self.DdAdicionais)
        self.plainTextEdit.setObjectName(u"plainTextEdit")
        self.plainTextEdit.setGeometry(QRect(390, 230, 321, 131))
        self.tabWidget.addTab(self.DdAdicionais, "")
        self.pushButton_3 = QPushButton(Dialog)
        self.pushButton_3.setObjectName(u"pushButton_3")
        self.pushButton_3.setGeometry(QRect(10, 400, 131, 41))
        self.pushButton_4 = QPushButton(Dialog)
        self.pushButton_4.setObjectName(u"pushButton_4")
        self.pushButton_4.setGeometry(QRect(590, 400, 131, 41))
        self.pushButton_4.setCheckable(False)
        self.pushButton_4.setChecked(False)
        self.pushButton_4.setAutoRepeat(False)
        self.pushButton_2 = QPushButton(Dialog)
        self.pushButton_2.setObjectName(u"pushButton_2")
        self.pushButton_2.setEnabled(True)
        self.pushButton_2.setGeometry(QRect(450, 400, 131, 41))
        self.pushButton_5 = QPushButton(Dialog)
        self.pushButton_5.setObjectName(u"pushButton_5")
        self.pushButton_5.setEnabled(False)
        self.pushButton_5.setGeometry(QRect(310, 400, 131, 41))

        self.retranslateUi(Dialog)

        self.tabWidget.setCurrentIndex(1)


        QMetaObject.connectSlotsByName(Dialog)
    # setupUi

    def retranslateUi(self, Dialog):
        Dialog.setWindowTitle(QCoreApplication.translate("Dialog", u"Dialog", None))
        self.label_2.setText(QCoreApplication.translate("Dialog", u"CNPJ :", None))
        self.label_4.setText(QCoreApplication.translate("Dialog", u"Banco :", None))
        self.lineEdit_2.setInputMask(QCoreApplication.translate("Dialog", u"##.###.###/####-##", None))
        self.lineEdit_2.setText(QCoreApplication.translate("Dialog", u"00.000.000/0000-00", None))
        self.checkBox.setText(QCoreApplication.translate("Dialog", u"Ativo", None))
        self.label.setText(QCoreApplication.translate("Dialog", u"Ag\u00eancia", None))
        self.label_3.setText(QCoreApplication.translate("Dialog", u"C\u00f3digo Febraban :", None))
        self.pushButton.setText(QCoreApplication.translate("Dialog", u"p", None))
        self.label_5.setText(QCoreApplication.translate("Dialog", u" -", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.DdPrincipal), QCoreApplication.translate("Dialog", u"Dados Principais", None))
        self.label_11.setText(QCoreApplication.translate("Dialog", u"Rua :", None))
        self.label_18.setText(QCoreApplication.translate("Dialog", u"N \u00ba :", None))
        self.label_19.setText(QCoreApplication.translate("Dialog", u"Bairro :", None))
        self.label_20.setText(QCoreApplication.translate("Dialog", u"Dados Complementares :", None))
        self.label_21.setText(QCoreApplication.translate("Dialog", u"CEP :", None))
        self.lineEdit_18.setInputMask(QCoreApplication.translate("Dialog", u"#####-###", None))
        self.label_22.setText(QCoreApplication.translate("Dialog", u"Cidade:", None))
        self.label_23.setText(QCoreApplication.translate("Dialog", u"UF :", None))
        self.label_24.setText(QCoreApplication.translate("Dialog", u"Celular:", None))
        self.lineEdit_21.setInputMask(QCoreApplication.translate("Dialog", u"(##) #####-####", None))
        self.lineEdit_21.setText(QCoreApplication.translate("Dialog", u"() ------", None))
        self.lineEdit_22.setInputMask(QCoreApplication.translate("Dialog", u"(##) ####-####", None))
        self.lineEdit_22.setText(QCoreApplication.translate("Dialog", u"() ------", None))
        self.label_25.setText(QCoreApplication.translate("Dialog", u"Telefone :", None))
        self.checkBox_4.setText(QCoreApplication.translate("Dialog", u"Possui WhatsApp ?", None))
        self.label_26.setText(QCoreApplication.translate("Dialog", u"E-mail :", None))
        self.lineEdit_23.setInputMask("")
        self.label_27.setText(QCoreApplication.translate("Dialog", u"Observa\u00e7\u00e3o :", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.DdAdicionais), QCoreApplication.translate("Dialog", u"Dados Adicionais", None))
        self.pushButton_3.setText(QCoreApplication.translate("Dialog", u"&Alterar", None))
        self.pushButton_4.setText(QCoreApplication.translate("Dialog", u"&Cancelar", None))
#if QT_CONFIG(shortcut)
        self.pushButton_4.setShortcut(QCoreApplication.translate("Dialog", u"Alt+C", None))
#endif // QT_CONFIG(shortcut)
        self.pushButton_2.setText(QCoreApplication.translate("Dialog", u"A&dicionar", None))
#if QT_CONFIG(shortcut)
        self.pushButton_2.setShortcut(QCoreApplication.translate("Dialog", u"Alt+D", None))
#endif // QT_CONFIG(shortcut)
        self.pushButton_5.setText(QCoreApplication.translate("Dialog", u"&Salvar", None))
#if QT_CONFIG(shortcut)
        self.pushButton_5.setShortcut("")
#endif // QT_CONFIG(shortcut)
    # retranslateUi

