# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'CadEmpresa.ui'
##
## Created by: Qt User Interface Compiler version 6.7.2
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QBrush, QColor, QConicalGradient, QCursor,
    QFont, QFontDatabase, QGradient, QIcon,
    QImage, QKeySequence, QLinearGradient, QPainter,
    QPalette, QPixmap, QRadialGradient, QTransform)
from PySide6.QtWidgets import (QApplication, QDateEdit, QLCDNumber, QLabel,
    QLineEdit, QMainWindow, QMenuBar, QPushButton,
    QSizePolicy, QStatusBar, QTabWidget, QWidget)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        if not MainWindow.objectName():
            MainWindow.setObjectName(u"MainWindow")
        MainWindow.resize(680, 480)
        MainWindow.setMinimumSize(QSize(680, 480))
        MainWindow.setMaximumSize(QSize(680, 480))
        self.centralwidget = QWidget(MainWindow)
        self.centralwidget.setObjectName(u"centralwidget")
        self.tabWidget = QTabWidget(self.centralwidget)
        self.tabWidget.setObjectName(u"tabWidget")
        self.tabWidget.setGeometry(QRect(0, 0, 680, 480))
        font = QFont()
        font.setStyleStrategy(QFont.PreferAntialias)
        self.tabWidget.setFont(font)
#if QT_CONFIG(tooltip)
        self.tabWidget.setToolTip(u"")
#endif // QT_CONFIG(tooltip)
        self.DdPrincipais = QWidget()
        self.DdPrincipais.setObjectName(u"DdPrincipais")
        self.lineEdit = QLineEdit(self.DdPrincipais)
        self.lineEdit.setObjectName(u"lineEdit")
        self.lineEdit.setGeometry(QRect(10, 50, 521, 21))
        font1 = QFont()
        font1.setFamilies([u"Segoe UI"])
        font1.setPointSize(12)
        font1.setStyleStrategy(QFont.NoAntialias)
        self.lineEdit.setFont(font1)
        self.label = QLabel(self.DdPrincipais)
        self.label.setObjectName(u"label")
        self.label.setGeometry(QRect(10, 30, 91, 16))
        font2 = QFont()
        font2.setFamilies([u"Segoe UI"])
        font2.setPointSize(12)
        self.label.setFont(font2)
        self.lineEdit_3 = QLineEdit(self.DdPrincipais)
        self.lineEdit_3.setObjectName(u"lineEdit_3")
        self.lineEdit_3.setGeometry(QRect(10, 100, 521, 21))
        self.lineEdit_3.setFont(font2)
        self.label_3 = QLabel(self.DdPrincipais)
        self.label_3.setObjectName(u"label_3")
        self.label_3.setGeometry(QRect(10, 80, 121, 16))
        self.label_3.setFont(font2)
        self.lineEdit_4 = QLineEdit(self.DdPrincipais)
        self.lineEdit_4.setObjectName(u"lineEdit_4")
        self.lineEdit_4.setGeometry(QRect(10, 150, 251, 21))
        self.lineEdit_4.setFont(font2)
        self.label_4 = QLabel(self.DdPrincipais)
        self.label_4.setObjectName(u"label_4")
        self.label_4.setGeometry(QRect(10, 130, 91, 16))
        self.label_4.setFont(font2)
        self.label_5 = QLabel(self.DdPrincipais)
        self.label_5.setObjectName(u"label_5")
        self.label_5.setGeometry(QRect(280, 130, 121, 16))
        self.label_5.setFont(font2)
        self.dateEdit = QDateEdit(self.DdPrincipais)
        self.dateEdit.setObjectName(u"dateEdit")
        self.dateEdit.setGeometry(QRect(280, 150, 131, 22))
        self.dateEdit.setCalendarPopup(True)
        self.pushButton = QPushButton(self.DdPrincipais)
        self.pushButton.setObjectName(u"pushButton")
        self.pushButton.setEnabled(False)
        self.pushButton.setGeometry(QRect(380, 360, 140, 48))
        font3 = QFont()
        font3.setFamilies([u"Segoe UI"])
        font3.setPointSize(12)
        font3.setBold(True)
        font3.setItalic(False)
        font3.setUnderline(False)
        self.pushButton.setFont(font3)
        self.pushButton_2 = QPushButton(self.DdPrincipais)
        self.pushButton_2.setObjectName(u"pushButton_2")
        self.pushButton_2.setEnabled(False)
        self.pushButton_2.setGeometry(QRect(530, 360, 140, 48))
        self.pushButton_2.setFont(font3)
#if QT_CONFIG(tooltip)
        self.pushButton_2.setToolTip(u"")
#endif // QT_CONFIG(tooltip)
        self.pushButton_3 = QPushButton(self.DdPrincipais)
        self.pushButton_3.setObjectName(u"pushButton_3")
        self.pushButton_3.setGeometry(QRect(20, 360, 140, 48))
        self.pushButton_3.setFont(font3)
        self.pushButton_3.setToolTipDuration(5)
        self.lcdNumber = QLCDNumber(self.DdPrincipais)
        self.lcdNumber.setObjectName(u"lcdNumber")
        self.lcdNumber.setGeometry(QRect(10, 0, 61, 23))
        self.lcdNumber.setProperty("intValue", 0)
        self.tabWidget.addTab(self.DdPrincipais, "")
        self.DdAdicionais = QWidget()
        self.DdAdicionais.setObjectName(u"DdAdicionais")
        self.tabWidget.addTab(self.DdAdicionais, "")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QMenuBar(MainWindow)
        self.menubar.setObjectName(u"menubar")
        self.menubar.setGeometry(QRect(0, 0, 680, 21))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QStatusBar(MainWindow)
        self.statusbar.setObjectName(u"statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)

        self.tabWidget.setCurrentIndex(0)


        QMetaObject.connectSlotsByName(MainWindow)
    # setupUi

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QCoreApplication.translate("MainWindow", u"MainWindow", None))
        self.label.setText(QCoreApplication.translate("MainWindow", u"Raz\u00e3o Social:", None))
        self.lineEdit_3.setText("")
        self.label_3.setText(QCoreApplication.translate("MainWindow", u"Nome Fantasia:", None))
        self.label_4.setText(QCoreApplication.translate("MainWindow", u"CNPJ/CPF:", None))
        self.label_5.setText(QCoreApplication.translate("MainWindow", u"Data de Abertura:", None))
        self.pushButton.setText(QCoreApplication.translate("MainWindow", u"&Salvar", None))
#if QT_CONFIG(shortcut)
        self.pushButton.setShortcut(QCoreApplication.translate("MainWindow", u"Alt+S", None))
#endif // QT_CONFIG(shortcut)
        self.pushButton_2.setText(QCoreApplication.translate("MainWindow", u"&Cancelar", None))
#if QT_CONFIG(shortcut)
        self.pushButton_2.setShortcut(QCoreApplication.translate("MainWindow", u"Alt+C", None))
#endif // QT_CONFIG(shortcut)
#if QT_CONFIG(tooltip)
        self.pushButton_3.setToolTip("")
#endif // QT_CONFIG(tooltip)
        self.pushButton_3.setText(QCoreApplication.translate("MainWindow", u"&Alterar", None))
#if QT_CONFIG(shortcut)
        self.pushButton_3.setShortcut(QCoreApplication.translate("MainWindow", u"Ctrl+A", None))
#endif // QT_CONFIG(shortcut)
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.DdPrincipais), QCoreApplication.translate("MainWindow", u"Dados Principais", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.DdAdicionais), QCoreApplication.translate("MainWindow", u"Dados Adicionais", None))
    # retranslateUi

