# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'CadFornecedor.ui'
##
## Created by: Qt User Interface Compiler version 6.7.3
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QBrush, QColor, QConicalGradient, QCursor,
    QFont, QFontDatabase, QGradient, QIcon,
    QImage, QKeySequence, QLinearGradient, QPainter,
    QPalette, QPixmap, QRadialGradient, QTransform)
from PySide6.QtWidgets import (QApplication, QCheckBox, QDateEdit, QDialog,
    QFrame, QGroupBox, QHBoxLayout, QLCDNumber,
    QLabel, QLayout, QLineEdit, QPlainTextEdit,
    QPushButton, QRadioButton, QSizePolicy, QSpacerItem,
    QTabWidget, QVBoxLayout, QWidget)

class Ui_CadFornecedor(object):
    def setupUi(self, CadFornecedor):
        if not CadFornecedor.objectName():
            CadFornecedor.setObjectName(u"CadFornecedor")
        CadFornecedor.resize(739, 594)
        CadFornecedor.setMinimumSize(QSize(726, 0))
        CadFornecedor.setMaximumSize(QSize(739, 601))
        self.verticalLayout = QVBoxLayout(CadFornecedor)
        self.verticalLayout.setObjectName(u"verticalLayout")
        self.tabWidget = QTabWidget(CadFornecedor)
        self.tabWidget.setObjectName(u"tabWidget")
        self.tabWidget.setMinimumSize(QSize(721, 491))
        self.tabWidget.setMaximumSize(QSize(721, 491))
        font = QFont()
        font.setFamilies([u"Segoe UI"])
        font.setPointSize(12)
        self.tabWidget.setFont(font)
        self.tabWidget.setCursor(QCursor(Qt.CursorShape.PointingHandCursor))
        self.tabWidget.setContextMenuPolicy(Qt.DefaultContextMenu)
        self.tabWidget.setAcceptDrops(False)
        self.tabWidget.setStyleSheet(u"font: 12pt \"Segoe UI\";")
        self.DdPrincipais = QWidget()
        self.DdPrincipais.setObjectName(u"DdPrincipais")
        self.lcd_id = QLCDNumber(self.DdPrincipais)
        self.lcd_id.setObjectName(u"lcd_id")
        self.lcd_id.setGeometry(QRect(20, 10, 91, 23))
        self.lcd_id.setFrameShape(QFrame.Box)
        self.lcd_id.setLineWidth(1)
        self.lcd_id.setSegmentStyle(QLCDNumber.Flat)
        self.lcd_id.setProperty(u"value", 0.000000000000000)
        self.lcd_id.setProperty(u"intValue", 0)
        self.label_10 = QLabel(self.DdPrincipais)
        self.label_10.setObjectName(u"label_10")
        self.label_10.setGeometry(QRect(20, 140, 121, 16))
        self.label_10.setFont(font)
        self.text_nome_fantasia = QLineEdit(self.DdPrincipais)
        self.text_nome_fantasia.setObjectName(u"text_nome_fantasia")
        self.text_nome_fantasia.setGeometry(QRect(20, 160, 591, 21))
        self.text_nome_fantasia.setFont(font)
        self.text_nome_fantasia.setReadOnly(True)
        self.text_razao_social = QLineEdit(self.DdPrincipais)
        self.text_razao_social.setObjectName(u"text_razao_social")
        self.text_razao_social.setGeometry(QRect(20, 110, 591, 21))
        font1 = QFont()
        font1.setFamilies([u"Segoe UI"])
        font1.setPointSize(12)
        font1.setStyleStrategy(QFont.NoAntialias)
        self.text_razao_social.setFont(font1)
        self.text_razao_social.setReadOnly(True)
        self.label = QLabel(self.DdPrincipais)
        self.label.setObjectName(u"label")
        self.label.setGeometry(QRect(20, 90, 91, 16))
        self.label.setFont(font)
        self.groupBox = QGroupBox(self.DdPrincipais)
        self.groupBox.setObjectName(u"groupBox")
        self.groupBox.setGeometry(QRect(20, 270, 591, 171))
        self.check_contribuinte = QCheckBox(self.groupBox)
        self.check_contribuinte.setObjectName(u"check_contribuinte")
        self.check_contribuinte.setEnabled(False)
        self.check_contribuinte.setGeometry(QRect(10, 40, 221, 17))
        self.check_contribuinte.setChecked(False)
        self.check_optante = QCheckBox(self.groupBox)
        self.check_optante.setObjectName(u"check_optante")
        self.check_optante.setEnabled(False)
        self.check_optante.setGeometry(QRect(10, 70, 281, 17))
        self.check_optante.setChecked(False)
        self.text_ramo = QLineEdit(self.groupBox)
        self.text_ramo.setObjectName(u"text_ramo")
        self.text_ramo.setGeometry(QRect(10, 120, 241, 21))
        self.text_ramo.setCursorPosition(0)
        self.text_ramo.setReadOnly(True)
        self.label_17 = QLabel(self.groupBox)
        self.label_17.setObjectName(u"label_17")
        self.label_17.setGeometry(QRect(10, 100, 141, 21))
        self.text_IE = QLineEdit(self.DdPrincipais)
        self.text_IE.setObjectName(u"text_IE")
        self.text_IE.setGeometry(QRect(20, 210, 241, 21))
        self.text_IE.setCursorPosition(0)
        self.text_IE.setReadOnly(True)
        self.label_14 = QLabel(self.DdPrincipais)
        self.label_14.setObjectName(u"label_14")
        self.label_14.setGeometry(QRect(20, 190, 141, 21))
        self.text_IM = QLineEdit(self.DdPrincipais)
        self.text_IM.setObjectName(u"text_IM")
        self.text_IM.setGeometry(QRect(270, 210, 241, 21))
        self.text_IM.setCursorPosition(0)
        self.text_IM.setReadOnly(True)
        self.label_16 = QLabel(self.DdPrincipais)
        self.label_16.setObjectName(u"label_16")
        self.label_16.setGeometry(QRect(270, 190, 141, 21))
        self.bnt_consulta_cnpj = QPushButton(self.DdPrincipais)
        self.bnt_consulta_cnpj.setObjectName(u"bnt_consulta_cnpj")
        self.bnt_consulta_cnpj.setGeometry(QRect(270, 55, 30, 30))
        self.bnt_consulta_cnpj.setMaximumSize(QSize(30, 30))
        self.bnt_consulta_cnpj.setStyleSheet(u"border: 1px solid #000000;\n"
"border-radius: 10px;\n"
"QPushButton:hover#bnt_consulta_cnpj{\n"
"   background-color:bluw;\n"
"}:")
        self.widget = QWidget(self.DdPrincipais)
        self.widget.setObjectName(u"widget")
        self.widget.setGeometry(QRect(380, 10, 312, 29))
        self.horizontalLayout_5 = QHBoxLayout(self.widget)
        self.horizontalLayout_5.setObjectName(u"horizontalLayout_5")
        self.horizontalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.checkBox = QCheckBox(self.widget)
        self.checkBox.setObjectName(u"checkBox")

        self.horizontalLayout_5.addWidget(self.checkBox)

        self.horizontalLayout_2 = QHBoxLayout()
        self.horizontalLayout_2.setObjectName(u"horizontalLayout_2")
        self.radio_fisica = QRadioButton(self.widget)
        self.radio_fisica.setObjectName(u"radio_fisica")
        self.radio_fisica.setEnabled(False)

        self.horizontalLayout_2.addWidget(self.radio_fisica)

        self.radio_juridirica = QRadioButton(self.widget)
        self.radio_juridirica.setObjectName(u"radio_juridirica")
        self.radio_juridirica.setEnabled(False)
        self.radio_juridirica.setChecked(True)

        self.horizontalLayout_2.addWidget(self.radio_juridirica)


        self.horizontalLayout_5.addLayout(self.horizontalLayout_2)

        self.widget1 = QWidget(self.DdPrincipais)
        self.widget1.setObjectName(u"widget1")
        self.widget1.setGeometry(QRect(21, 41, 243, 44))
        self.verticalLayout_2 = QVBoxLayout(self.widget1)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName(u"verticalLayout_2")
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.label_13 = QLabel(self.widget1)
        self.label_13.setObjectName(u"label_13")

        self.verticalLayout_2.addWidget(self.label_13)

        self.text_cnpj = QLineEdit(self.widget1)
        self.text_cnpj.setObjectName(u"text_cnpj")
        self.text_cnpj.setMinimumSize(QSize(241, 21))
        self.text_cnpj.setMaximumSize(QSize(241, 21))
        self.text_cnpj.setCursorPosition(0)
        self.text_cnpj.setReadOnly(True)

        self.verticalLayout_2.addWidget(self.text_cnpj)

        self.widget2 = QWidget(self.DdPrincipais)
        self.widget2.setObjectName(u"widget2")
        self.widget2.setGeometry(QRect(310, 40, 133, 45))
        self.verticalLayout_3 = QVBoxLayout(self.widget2)
        self.verticalLayout_3.setSpacing(0)
        self.verticalLayout_3.setObjectName(u"verticalLayout_3")
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.label_15 = QLabel(self.widget2)
        self.label_15.setObjectName(u"label_15")
        self.label_15.setFont(font)

        self.verticalLayout_3.addWidget(self.label_15)

        self.Dt_abertura = QDateEdit(self.widget2)
        self.Dt_abertura.setObjectName(u"Dt_abertura")
        self.Dt_abertura.setMinimumSize(QSize(131, 22))
        self.Dt_abertura.setMaximumSize(QSize(131, 22))
        self.Dt_abertura.setReadOnly(True)
        self.Dt_abertura.setCalendarPopup(True)

        self.verticalLayout_3.addWidget(self.Dt_abertura)

        self.tabWidget.addTab(self.DdPrincipais, "")
        self.DdAdicionais = QWidget()
        self.DdAdicionais.setObjectName(u"DdAdicionais")
        self.text_complementar = QLineEdit(self.DdAdicionais)
        self.text_complementar.setObjectName(u"text_complementar")
        self.text_complementar.setGeometry(QRect(320, 70, 321, 21))
        self.text_complementar.setReadOnly(True)
        self.text_numero = QLineEdit(self.DdAdicionais)
        self.text_numero.setObjectName(u"text_numero")
        self.text_numero.setGeometry(QRect(520, 30, 121, 21))
        self.text_numero.setReadOnly(True)
        self.text_rua = QLineEdit(self.DdAdicionais)
        self.text_rua.setObjectName(u"text_rua")
        self.text_rua.setGeometry(QRect(10, 30, 501, 21))
        self.text_rua.setReadOnly(True)
        self.label_28 = QLabel(self.DdAdicionais)
        self.label_28.setObjectName(u"label_28")
        self.label_28.setGeometry(QRect(320, 50, 211, 21))
        self.text_cep = QLineEdit(self.DdAdicionais)
        self.text_cep.setObjectName(u"text_cep")
        self.text_cep.setGeometry(QRect(10, 120, 161, 21))
        self.text_cep.setReadOnly(True)
        self.text_bairro = QLineEdit(self.DdAdicionais)
        self.text_bairro.setObjectName(u"text_bairro")
        self.text_bairro.setGeometry(QRect(10, 70, 291, 21))
        self.text_bairro.setReadOnly(True)
        self.text_telefone = QLineEdit(self.DdAdicionais)
        self.text_telefone.setObjectName(u"text_telefone")
        self.text_telefone.setGeometry(QRect(460, 180, 181, 21))
        self.text_telefone.setMaxLength(14)
        self.text_telefone.setReadOnly(True)
        self.text_telefone.setCursorMoveStyle(Qt.VisualMoveStyle)
        self.plain_text = QPlainTextEdit(self.DdAdicionais)
        self.plain_text.setObjectName(u"plain_text")
        self.plain_text.setGeometry(QRect(370, 230, 271, 131))
        self.plain_text.setReadOnly(True)
        self.check_p_whats = QCheckBox(self.DdAdicionais)
        self.check_p_whats.setObjectName(u"check_p_whats")
        self.check_p_whats.setGeometry(QRect(210, 180, 151, 17))
        self.check_p_whats.setChecked(False)
        self.label_29 = QLabel(self.DdAdicionais)
        self.label_29.setObjectName(u"label_29")
        self.label_29.setGeometry(QRect(520, 10, 141, 21))
        self.text_email = QLineEdit(self.DdAdicionais)
        self.text_email.setObjectName(u"text_email")
        self.text_email.setGeometry(QRect(10, 230, 351, 21))
        self.text_email.setReadOnly(True)
        self.label_30 = QLabel(self.DdAdicionais)
        self.label_30.setObjectName(u"label_30")
        self.label_30.setGeometry(QRect(490, 100, 141, 21))
        self.label_31 = QLabel(self.DdAdicionais)
        self.label_31.setObjectName(u"label_31")
        self.label_31.setGeometry(QRect(10, 160, 131, 16))
        self.label_12 = QLabel(self.DdAdicionais)
        self.label_12.setObjectName(u"label_12")
        self.label_12.setGeometry(QRect(10, 10, 141, 21))
        self.label_32 = QLabel(self.DdAdicionais)
        self.label_32.setObjectName(u"label_32")
        self.label_32.setGeometry(QRect(370, 210, 131, 16))
        self.text_uf = QLineEdit(self.DdAdicionais)
        self.text_uf.setObjectName(u"text_uf")
        self.text_uf.setGeometry(QRect(490, 120, 151, 21))
        self.text_uf.setInputMethodHints(Qt.ImhNoAutoUppercase)
        self.text_uf.setMaxLength(2)
        self.text_uf.setReadOnly(True)
        self.text_cidade = QLineEdit(self.DdAdicionais)
        self.text_cidade.setObjectName(u"text_cidade")
        self.text_cidade.setGeometry(QRect(190, 120, 291, 21))
        self.text_cidade.setReadOnly(True)
        self.text_celular = QLineEdit(self.DdAdicionais)
        self.text_celular.setObjectName(u"text_celular")
        self.text_celular.setGeometry(QRect(10, 180, 181, 21))
        self.text_celular.setMaxLength(15)
        self.text_celular.setReadOnly(True)
        self.text_celular.setCursorMoveStyle(Qt.VisualMoveStyle)
        self.label_33 = QLabel(self.DdAdicionais)
        self.label_33.setObjectName(u"label_33")
        self.label_33.setGeometry(QRect(10, 50, 141, 21))
        self.label_34 = QLabel(self.DdAdicionais)
        self.label_34.setObjectName(u"label_34")
        self.label_34.setGeometry(QRect(10, 100, 141, 21))
        self.label_35 = QLabel(self.DdAdicionais)
        self.label_35.setObjectName(u"label_35")
        self.label_35.setGeometry(QRect(10, 210, 131, 16))
        self.label_36 = QLabel(self.DdAdicionais)
        self.label_36.setObjectName(u"label_36")
        self.label_36.setGeometry(QRect(460, 160, 131, 16))
        self.label_37 = QLabel(self.DdAdicionais)
        self.label_37.setObjectName(u"label_37")
        self.label_37.setGeometry(QRect(190, 100, 141, 21))
        self.tabWidget.addTab(self.DdAdicionais, "")

        self.verticalLayout.addWidget(self.tabWidget)

        self.frame = QFrame(CadFornecedor)
        self.frame.setObjectName(u"frame")
        self.frame.setFrameShape(QFrame.StyledPanel)
        self.frame.setFrameShadow(QFrame.Raised)
        self.widget3 = QWidget(self.frame)
        self.widget3.setObjectName(u"widget3")
        self.widget3.setGeometry(QRect(350, 0, 366, 25))
        self.horizontalLayout_3 = QHBoxLayout(self.widget3)
        self.horizontalLayout_3.setObjectName(u"horizontalLayout_3")
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.back_full = QPushButton(self.widget3)
        self.back_full.setObjectName(u"back_full")

        self.horizontalLayout_3.addWidget(self.back_full)

        self.back = QPushButton(self.widget3)
        self.back.setObjectName(u"back")

        self.horizontalLayout_3.addWidget(self.back)

        self.horizontalSpacer_2 = QSpacerItem(20, 20, QSizePolicy.Policy.Minimum, QSizePolicy.Policy.Minimum)

        self.horizontalLayout_3.addItem(self.horizontalSpacer_2)

        self.next = QPushButton(self.widget3)
        self.next.setObjectName(u"next")

        self.horizontalLayout_3.addWidget(self.next)

        self.next_full = QPushButton(self.widget3)
        self.next_full.setObjectName(u"next_full")

        self.horizontalLayout_3.addWidget(self.next_full)


        self.verticalLayout.addWidget(self.frame)

        self.horizontalLayout = QHBoxLayout()
        self.horizontalLayout.setSpacing(6)
        self.horizontalLayout.setObjectName(u"horizontalLayout")
        self.horizontalLayout.setSizeConstraint(QLayout.SetDefaultConstraint)
        self.horizontalLayout.setContentsMargins(0, -1, -1, -1)
        self.bnt_alterar = QPushButton(CadFornecedor)
        self.bnt_alterar.setObjectName(u"bnt_alterar")
        self.bnt_alterar.setMinimumSize(QSize(100, 30))
        self.bnt_alterar.setMaximumSize(QSize(131, 41))

        self.horizontalLayout.addWidget(self.bnt_alterar)

        self.horizontalSpacer = QSpacerItem(58, 20, QSizePolicy.Policy.Expanding, QSizePolicy.Policy.Minimum)

        self.horizontalLayout.addItem(self.horizontalSpacer)

        self.bnt_adicionar = QPushButton(CadFornecedor)
        self.bnt_adicionar.setObjectName(u"bnt_adicionar")
        self.bnt_adicionar.setEnabled(True)
        self.bnt_adicionar.setMinimumSize(QSize(100, 0))
        self.bnt_adicionar.setMaximumSize(QSize(131, 41))

        self.horizontalLayout.addWidget(self.bnt_adicionar)

        self.bnt_salvar = QPushButton(CadFornecedor)
        self.bnt_salvar.setObjectName(u"bnt_salvar")
        self.bnt_salvar.setEnabled(False)
        self.bnt_salvar.setMinimumSize(QSize(100, 0))
        self.bnt_salvar.setMaximumSize(QSize(131, 41))

        self.horizontalLayout.addWidget(self.bnt_salvar)

        self.bnt_search = QPushButton(CadFornecedor)
        self.bnt_search.setObjectName(u"bnt_search")
        self.bnt_search.setMinimumSize(QSize(100, 0))
        self.bnt_search.setMaximumSize(QSize(131, 41))
        self.bnt_search.setCheckable(False)
        self.bnt_search.setChecked(False)
        self.bnt_search.setAutoRepeat(False)

        self.horizontalLayout.addWidget(self.bnt_search)

        self.bnt_excluir = QPushButton(CadFornecedor)
        self.bnt_excluir.setObjectName(u"bnt_excluir")
        self.bnt_excluir.setMinimumSize(QSize(100, 0))
        self.bnt_excluir.setMaximumSize(QSize(131, 41))
        self.bnt_excluir.setCheckable(False)
        self.bnt_excluir.setChecked(False)
        self.bnt_excluir.setAutoRepeat(False)

        self.horizontalLayout.addWidget(self.bnt_excluir)

        self.bnt_cancelar = QPushButton(CadFornecedor)
        self.bnt_cancelar.setObjectName(u"bnt_cancelar")
        self.bnt_cancelar.setMinimumSize(QSize(100, 0))
        self.bnt_cancelar.setMaximumSize(QSize(131, 41))
        self.bnt_cancelar.setCheckable(False)
        self.bnt_cancelar.setChecked(False)
        self.bnt_cancelar.setAutoRepeat(False)

        self.horizontalLayout.addWidget(self.bnt_cancelar)


        self.verticalLayout.addLayout(self.horizontalLayout)


        self.retranslateUi(CadFornecedor)

        self.tabWidget.setCurrentIndex(0)


        QMetaObject.connectSlotsByName(CadFornecedor)
    # setupUi

    def retranslateUi(self, CadFornecedor):
        CadFornecedor.setWindowTitle(QCoreApplication.translate("CadFornecedor", u"Cadastro da Empresa", None))
        self.label_10.setText(QCoreApplication.translate("CadFornecedor", u"Nome Fantasia:", None))
        self.text_nome_fantasia.setText("")
        self.label.setText(QCoreApplication.translate("CadFornecedor", u"Raz\u00e3o Social:", None))
        self.groupBox.setTitle(QCoreApplication.translate("CadFornecedor", u"Outras Informa\u00e7\u00f5es", None))
        self.check_contribuinte.setText(QCoreApplication.translate("CadFornecedor", u"Contribuinte ?", None))
        self.check_optante.setText(QCoreApplication.translate("CadFornecedor", u"Optante Pelo Simples Nacional ?", None))
        self.text_ramo.setInputMask("")
        self.text_ramo.setText("")
        self.label_17.setText(QCoreApplication.translate("CadFornecedor", u"Ramo de Atividade :", None))
        self.text_IE.setInputMask("")
        self.text_IE.setText("")
        self.label_14.setText(QCoreApplication.translate("CadFornecedor", u"Inscri\u00e7\u00e3o Estadual :", None))
        self.text_IM.setInputMask("")
        self.text_IM.setText("")
        self.label_16.setText(QCoreApplication.translate("CadFornecedor", u"Inscri\u00e7\u00e3o Municipal :", None))
        self.bnt_consulta_cnpj.setText(QCoreApplication.translate("CadFornecedor", u"P", None))
        self.checkBox.setText(QCoreApplication.translate("CadFornecedor", u"Ativo", None))
        self.radio_fisica.setText(QCoreApplication.translate("CadFornecedor", u"Pessoa Fis\u00edca", None))
        self.radio_juridirica.setText(QCoreApplication.translate("CadFornecedor", u"Pessoa juridica", None))
        self.label_13.setText(QCoreApplication.translate("CadFornecedor", u"CNPJ / CPF :", None))
        self.text_cnpj.setInputMask("")
        self.text_cnpj.setText("")
        self.label_15.setText(QCoreApplication.translate("CadFornecedor", u"Data de Abertura:", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.DdPrincipais), QCoreApplication.translate("CadFornecedor", u"Dados Principais", None))
        self.label_28.setText(QCoreApplication.translate("CadFornecedor", u"Dados Complementares :", None))
        self.text_cep.setInputMask(QCoreApplication.translate("CadFornecedor", u"#####-###", None))
        self.text_telefone.setInputMask(QCoreApplication.translate("CadFornecedor", u"(##) ####-####", None))
        self.text_telefone.setText(QCoreApplication.translate("CadFornecedor", u"() ------", None))
        self.check_p_whats.setText(QCoreApplication.translate("CadFornecedor", u"Possui WhatsApp ?", None))
        self.label_29.setText(QCoreApplication.translate("CadFornecedor", u"N \u00ba :", None))
        self.text_email.setInputMask("")
        self.label_30.setText(QCoreApplication.translate("CadFornecedor", u"UF :", None))
        self.label_31.setText(QCoreApplication.translate("CadFornecedor", u"Celular:", None))
        self.label_12.setText(QCoreApplication.translate("CadFornecedor", u"Rua :", None))
        self.label_32.setText(QCoreApplication.translate("CadFornecedor", u"Observa\u00e7\u00e3o :", None))
        self.text_celular.setInputMask(QCoreApplication.translate("CadFornecedor", u"(##) #####-####", None))
        self.text_celular.setText(QCoreApplication.translate("CadFornecedor", u"() ------", None))
        self.label_33.setText(QCoreApplication.translate("CadFornecedor", u"Bairro :", None))
        self.label_34.setText(QCoreApplication.translate("CadFornecedor", u"CEP :", None))
        self.label_35.setText(QCoreApplication.translate("CadFornecedor", u"E-mail :", None))
        self.label_36.setText(QCoreApplication.translate("CadFornecedor", u"Telefone :", None))
        self.label_37.setText(QCoreApplication.translate("CadFornecedor", u"Cidade:", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.DdAdicionais), QCoreApplication.translate("CadFornecedor", u"Dados Adicionais", None))
#if QT_CONFIG(tooltip)
        self.back_full.setToolTip(QCoreApplication.translate("CadFornecedor", u"<html><head/><body><p>Ir para o primeiro...</p></body></html>", None))
#endif // QT_CONFIG(tooltip)
        self.back_full.setText(QCoreApplication.translate("CadFornecedor", u"<<", None))
#if QT_CONFIG(tooltip)
        self.back.setToolTip(QCoreApplication.translate("CadFornecedor", u"<html><head/><body><p>Voltar...</p></body></html>", None))
#endif // QT_CONFIG(tooltip)
        self.back.setText(QCoreApplication.translate("CadFornecedor", u"<", None))
#if QT_CONFIG(tooltip)
        self.next.setToolTip(QCoreApplication.translate("CadFornecedor", u"<html><head/><body><p>Pr\u00f3ximo...</p></body></html>", None))
#endif // QT_CONFIG(tooltip)
        self.next.setText(QCoreApplication.translate("CadFornecedor", u">", None))
#if QT_CONFIG(tooltip)
        self.next_full.setToolTip(QCoreApplication.translate("CadFornecedor", u"<html><head/><body><p><span style=\" font-weight:600;\">Ir para o fim.</span></p></body></html>", None))
#endif // QT_CONFIG(tooltip)
        self.next_full.setText(QCoreApplication.translate("CadFornecedor", u">>", None))
        self.bnt_alterar.setText(QCoreApplication.translate("CadFornecedor", u"&Alterar", None))
        self.bnt_adicionar.setText(QCoreApplication.translate("CadFornecedor", u"&Incluir", None))
#if QT_CONFIG(shortcut)
        self.bnt_adicionar.setShortcut(QCoreApplication.translate("CadFornecedor", u"Alt+I", None))
#endif // QT_CONFIG(shortcut)
        self.bnt_salvar.setText(QCoreApplication.translate("CadFornecedor", u"&Salvar", None))
#if QT_CONFIG(shortcut)
        self.bnt_salvar.setShortcut("")
#endif // QT_CONFIG(shortcut)
        self.bnt_search.setText(QCoreApplication.translate("CadFornecedor", u"&Pesquisar", None))
#if QT_CONFIG(shortcut)
        self.bnt_search.setShortcut(QCoreApplication.translate("CadFornecedor", u"Alt+P", None))
#endif // QT_CONFIG(shortcut)
        self.bnt_excluir.setText(QCoreApplication.translate("CadFornecedor", u"&Excluir", None))
#if QT_CONFIG(shortcut)
        self.bnt_excluir.setShortcut(QCoreApplication.translate("CadFornecedor", u"Alt+E", None))
#endif // QT_CONFIG(shortcut)
        self.bnt_cancelar.setText(QCoreApplication.translate("CadFornecedor", u"&Cancelar", None))
#if QT_CONFIG(shortcut)
        self.bnt_cancelar.setShortcut(QCoreApplication.translate("CadFornecedor", u"Alt+C", None))
#endif // QT_CONFIG(shortcut)
    # retranslateUi

