# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'CadUser.ui'
##
## Created by: Qt User Interface Compiler version 6.7.3
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QBrush, QColor, QConicalGradient, QCursor,
    QFont, QFontDatabase, QGradient, QIcon,
    QImage, QKeySequence, QLinearGradient, QPainter,
    QPalette, QPixmap, QRadialGradient, QTransform)
from PySide6.QtWidgets import (QAbstractSpinBox, QApplication, QCheckBox, QDateEdit,
    QDialog, QGroupBox, QLCDNumber, QLabel,
    QLineEdit, QPlainTextEdit, QPushButton, QSizePolicy,
    QTabWidget, QWidget)

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        if not Dialog.objectName():
            Dialog.setObjectName(u"Dialog")
        Dialog.resize(762, 611)
        self.tabWidget = QTabWidget(Dialog)
        self.tabWidget.setObjectName(u"tabWidget")
        self.tabWidget.setGeometry(QRect(0, 0, 761, 541))
        font = QFont()
        font.setFamilies([u"Segoe UI"])
        font.setPointSize(12)
        self.tabWidget.setFont(font)
        self.tabWidget.setCursor(QCursor(Qt.CursorShape.PointingHandCursor))
        self.tabWidget.setContextMenuPolicy(Qt.DefaultContextMenu)
        self.tabWidget.setAcceptDrops(False)
        self.tabWidget.setStyleSheet(u"font: 12pt \"Segoe UI\";")
        self.tabWidget.setTabShape(QTabWidget.Triangular)
        self.tabWidget.setElideMode(Qt.ElideLeft)
        self.DdPrincipais = QWidget()
        self.DdPrincipais.setObjectName(u"DdPrincipais")
        self.label = QLabel(self.DdPrincipais)
        self.label.setObjectName(u"label")
        self.label.setGeometry(QRect(20, 50, 131, 16))
        self.lineEdit = QLineEdit(self.DdPrincipais)
        self.lineEdit.setObjectName(u"lineEdit")
        self.lineEdit.setGeometry(QRect(20, 70, 591, 21))
        self.label_2 = QLabel(self.DdPrincipais)
        self.label_2.setObjectName(u"label_2")
        self.label_2.setGeometry(QRect(20, 100, 131, 16))
        self.lineEdit_2 = QLineEdit(self.DdPrincipais)
        self.lineEdit_2.setObjectName(u"lineEdit_2")
        self.lineEdit_2.setGeometry(QRect(20, 120, 591, 21))
        self.label_3 = QLabel(self.DdPrincipais)
        self.label_3.setObjectName(u"label_3")
        self.label_3.setGeometry(QRect(20, 150, 131, 16))
        self.lineEdit_3 = QLineEdit(self.DdPrincipais)
        self.lineEdit_3.setObjectName(u"lineEdit_3")
        self.lineEdit_3.setGeometry(QRect(20, 170, 181, 21))
        self.lineEdit_3.setMaxLength(15)
        self.lineEdit_3.setCursorMoveStyle(Qt.VisualMoveStyle)
        self.label_4 = QLabel(self.DdPrincipais)
        self.label_4.setObjectName(u"label_4")
        self.label_4.setGeometry(QRect(220, 150, 151, 16))
        self.dateEdit = QDateEdit(self.DdPrincipais)
        self.dateEdit.setObjectName(u"dateEdit")
        self.dateEdit.setGeometry(QRect(220, 170, 151, 22))
        self.dateEdit.setWrapping(True)
        self.dateEdit.setSpecialValueText(u"")
        self.dateEdit.setCorrectionMode(QAbstractSpinBox.CorrectToNearestValue)
        self.dateEdit.setKeyboardTracking(False)
        self.dateEdit.setProperty(u"showGroupSeparator", True)
        self.dateEdit.setCalendarPopup(True)
        self.groupBox = QGroupBox(self.DdPrincipais)
        self.groupBox.setObjectName(u"groupBox")
        self.groupBox.setGeometry(QRect(10, 210, 341, 281))
        self.lineEdit_4 = QLineEdit(self.groupBox)
        self.lineEdit_4.setObjectName(u"lineEdit_4")
        self.lineEdit_4.setGeometry(QRect(10, 100, 251, 21))
        self.lineEdit_4.setEchoMode(QLineEdit.PasswordEchoOnEdit)
        self.lineEdit_4.setDragEnabled(False)
        self.lineEdit_4.setReadOnly(False)
        self.label_5 = QLabel(self.groupBox)
        self.label_5.setObjectName(u"label_5")
        self.label_5.setGeometry(QRect(10, 30, 131, 16))
        self.lineEdit_5 = QLineEdit(self.groupBox)
        self.lineEdit_5.setObjectName(u"lineEdit_5")
        self.lineEdit_5.setGeometry(QRect(10, 50, 251, 21))
        self.label_6 = QLabel(self.groupBox)
        self.label_6.setObjectName(u"label_6")
        self.label_6.setGeometry(QRect(10, 80, 131, 16))
        self.groupBox_2 = QGroupBox(self.DdPrincipais)
        self.groupBox_2.setObjectName(u"groupBox_2")
        self.groupBox_2.setGeometry(QRect(360, 210, 331, 281))
        self.checkBox = QCheckBox(self.groupBox_2)
        self.checkBox.setObjectName(u"checkBox")
        self.checkBox.setGeometry(QRect(10, 40, 301, 17))
        self.checkBox_2 = QCheckBox(self.groupBox_2)
        self.checkBox_2.setObjectName(u"checkBox_2")
        self.checkBox_2.setGeometry(QRect(10, 60, 301, 17))
        self.checkBox_2.setChecked(True)
        self.checkBox_3 = QCheckBox(self.groupBox_2)
        self.checkBox_3.setObjectName(u"checkBox_3")
        self.checkBox_3.setGeometry(QRect(10, 80, 301, 17))
        self.label_7 = QLabel(self.groupBox_2)
        self.label_7.setObjectName(u"label_7")
        self.label_7.setGeometry(QRect(10, 110, 131, 16))
        self.plainTextEdit = QPlainTextEdit(self.groupBox_2)
        self.plainTextEdit.setObjectName(u"plainTextEdit")
        self.plainTextEdit.setGeometry(QRect(10, 130, 311, 141))
        self.lcdNumber = QLCDNumber(self.DdPrincipais)
        self.lcdNumber.setObjectName(u"lcdNumber")
        self.lcdNumber.setGeometry(QRect(20, 10, 91, 23))
        self.label_8 = QLabel(self.DdPrincipais)
        self.label_8.setObjectName(u"label_8")
        self.label_8.setGeometry(QRect(380, 150, 141, 21))
        self.lineEdit_6 = QLineEdit(self.DdPrincipais)
        self.lineEdit_6.setObjectName(u"lineEdit_6")
        self.lineEdit_6.setGeometry(QRect(380, 170, 241, 21))
        self.lineEdit_6.setCursorPosition(14)
        self.lineEdit_6.setCursorMoveStyle(Qt.VisualMoveStyle)
        self.tabWidget.addTab(self.DdPrincipais, "")
        self.DdAdicionais = QWidget()
        self.DdAdicionais.setObjectName(u"DdAdicionais")
        self.lineEdit_29 = QLineEdit(self.DdAdicionais)
        self.lineEdit_29.setObjectName(u"lineEdit_29")
        self.lineEdit_29.setGeometry(QRect(10, 230, 351, 21))
        self.lineEdit_25 = QLineEdit(self.DdAdicionais)
        self.lineEdit_25.setObjectName(u"lineEdit_25")
        self.lineEdit_25.setGeometry(QRect(520, 30, 121, 21))
        self.lineEdit_24 = QLineEdit(self.DdAdicionais)
        self.lineEdit_24.setObjectName(u"lineEdit_24")
        self.lineEdit_24.setGeometry(QRect(320, 70, 321, 21))
        self.lineEdit_30 = QLineEdit(self.DdAdicionais)
        self.lineEdit_30.setObjectName(u"lineEdit_30")
        self.lineEdit_30.setGeometry(QRect(490, 120, 151, 21))
        self.lineEdit_30.setInputMethodHints(Qt.ImhNoAutoUppercase)
        self.lineEdit_30.setMaxLength(2)
        self.lineEdit_32 = QLineEdit(self.DdAdicionais)
        self.lineEdit_32.setObjectName(u"lineEdit_32")
        self.lineEdit_32.setGeometry(QRect(10, 180, 181, 21))
        self.lineEdit_32.setMaxLength(15)
        self.lineEdit_32.setCursorMoveStyle(Qt.VisualMoveStyle)
        self.label_28 = QLabel(self.DdAdicionais)
        self.label_28.setObjectName(u"label_28")
        self.label_28.setGeometry(QRect(320, 50, 211, 21))
        self.label_31 = QLabel(self.DdAdicionais)
        self.label_31.setObjectName(u"label_31")
        self.label_31.setGeometry(QRect(10, 160, 131, 16))
        self.label_35 = QLabel(self.DdAdicionais)
        self.label_35.setObjectName(u"label_35")
        self.label_35.setGeometry(QRect(10, 210, 131, 16))
        self.label_34 = QLabel(self.DdAdicionais)
        self.label_34.setObjectName(u"label_34")
        self.label_34.setGeometry(QRect(10, 100, 141, 21))
        self.lineEdit_10 = QLineEdit(self.DdAdicionais)
        self.lineEdit_10.setObjectName(u"lineEdit_10")
        self.lineEdit_10.setGeometry(QRect(10, 30, 501, 21))
        self.label_32 = QLabel(self.DdAdicionais)
        self.label_32.setObjectName(u"label_32")
        self.label_32.setGeometry(QRect(10, 260, 131, 16))
        self.label_29 = QLabel(self.DdAdicionais)
        self.label_29.setObjectName(u"label_29")
        self.label_29.setGeometry(QRect(520, 10, 141, 21))
        self.lineEdit_31 = QLineEdit(self.DdAdicionais)
        self.lineEdit_31.setObjectName(u"lineEdit_31")
        self.lineEdit_31.setGeometry(QRect(190, 120, 291, 21))
        self.label_33 = QLabel(self.DdAdicionais)
        self.label_33.setObjectName(u"label_33")
        self.label_33.setGeometry(QRect(10, 50, 141, 21))
        self.label_30 = QLabel(self.DdAdicionais)
        self.label_30.setObjectName(u"label_30")
        self.label_30.setGeometry(QRect(490, 100, 141, 21))
        self.label_37 = QLabel(self.DdAdicionais)
        self.label_37.setObjectName(u"label_37")
        self.label_37.setGeometry(QRect(190, 100, 141, 21))
        self.lineEdit_27 = QLineEdit(self.DdAdicionais)
        self.lineEdit_27.setObjectName(u"lineEdit_27")
        self.lineEdit_27.setGeometry(QRect(10, 70, 291, 21))
        self.plainTextEdit_2 = QPlainTextEdit(self.DdAdicionais)
        self.plainTextEdit_2.setObjectName(u"plainTextEdit_2")
        self.plainTextEdit_2.setGeometry(QRect(10, 280, 321, 131))
        self.label_12 = QLabel(self.DdAdicionais)
        self.label_12.setObjectName(u"label_12")
        self.label_12.setGeometry(QRect(10, 10, 141, 21))
        self.lineEdit_26 = QLineEdit(self.DdAdicionais)
        self.lineEdit_26.setObjectName(u"lineEdit_26")
        self.lineEdit_26.setGeometry(QRect(10, 120, 161, 21))
        self.checkBox_5 = QCheckBox(self.DdAdicionais)
        self.checkBox_5.setObjectName(u"checkBox_5")
        self.checkBox_5.setGeometry(QRect(210, 180, 151, 17))
        self.checkBox_5.setChecked(False)
        self.groupBox_3 = QGroupBox(self.DdAdicionais)
        self.groupBox_3.setObjectName(u"groupBox_3")
        self.groupBox_3.setGeometry(QRect(380, 160, 261, 251))
        self.checkBox_4 = QCheckBox(self.groupBox_3)
        self.checkBox_4.setObjectName(u"checkBox_4")
        self.checkBox_4.setGeometry(QRect(20, 30, 201, 17))
        self.checkBox_6 = QCheckBox(self.groupBox_3)
        self.checkBox_6.setObjectName(u"checkBox_6")
        self.checkBox_6.setGeometry(QRect(20, 50, 221, 17))
        self.tabWidget.addTab(self.DdAdicionais, "")
        self.Permission = QWidget()
        self.Permission.setObjectName(u"Permission")
        self.tabWidget.addTab(self.Permission, "")
        self.pushButton_3 = QPushButton(Dialog)
        self.pushButton_3.setObjectName(u"pushButton_3")
        self.pushButton_3.setGeometry(QRect(610, 560, 131, 41))
        self.pushButton_3.setCheckable(False)
        self.pushButton_3.setChecked(False)
        self.pushButton_3.setAutoRepeat(False)
        self.pushButton_2 = QPushButton(Dialog)
        self.pushButton_2.setObjectName(u"pushButton_2")
        self.pushButton_2.setEnabled(True)
        self.pushButton_2.setGeometry(QRect(470, 560, 131, 41))
        self.pushButton = QPushButton(Dialog)
        self.pushButton.setObjectName(u"pushButton")
        self.pushButton.setGeometry(QRect(20, 560, 131, 41))
        self.pushButton_4 = QPushButton(Dialog)
        self.pushButton_4.setObjectName(u"pushButton_4")
        self.pushButton_4.setEnabled(False)
        self.pushButton_4.setGeometry(QRect(330, 560, 131, 41))

        self.retranslateUi(Dialog)

        self.tabWidget.setCurrentIndex(1)


        QMetaObject.connectSlotsByName(Dialog)
    # setupUi

    def retranslateUi(self, Dialog):
        Dialog.setWindowTitle(QCoreApplication.translate("Dialog", u"Dialog", None))
        self.label.setText(QCoreApplication.translate("Dialog", u"Nome Completo:", None))
        self.lineEdit.setInputMask("")
        self.label_2.setText(QCoreApplication.translate("Dialog", u"E-mail :", None))
        self.lineEdit_2.setInputMask("")
        self.label_3.setText(QCoreApplication.translate("Dialog", u"Telefone :", None))
        self.lineEdit_3.setInputMask(QCoreApplication.translate("Dialog", u"(##) #####-####", None))
        self.lineEdit_3.setText(QCoreApplication.translate("Dialog", u"() -----", None))
        self.label_4.setText(QCoreApplication.translate("Dialog", u"Data de Nascimento:", None))
        self.groupBox.setTitle(QCoreApplication.translate("Dialog", u"Configura\u00e7\u00f5es de usu\u00e1rio", None))
        self.lineEdit_4.setInputMask("")
        self.lineEdit_4.setText("")
        self.label_5.setText(QCoreApplication.translate("Dialog", u"Usu\u00e1rio :", None))
        self.lineEdit_5.setInputMask("")
        self.lineEdit_5.setText("")
        self.label_6.setText(QCoreApplication.translate("Dialog", u"Senha :", None))
        self.groupBox_2.setTitle(QCoreApplication.translate("Dialog", u"Op\u00e7\u00f5es de Usu\u00e1rio :", None))
        self.checkBox.setText(QCoreApplication.translate("Dialog", u"Resetar Senha", None))
        self.checkBox_2.setText(QCoreApplication.translate("Dialog", u"Primeiro Acesso", None))
        self.checkBox_3.setText(QCoreApplication.translate("Dialog", u"Bloqueado", None))
        self.label_7.setText(QCoreApplication.translate("Dialog", u"Observa\u00e7\u00f5es:", None))
        self.label_8.setText(QCoreApplication.translate("Dialog", u"CPF :", None))
        self.lineEdit_6.setInputMask(QCoreApplication.translate("Dialog", u"###.###.###-##", None))
        self.lineEdit_6.setText(QCoreApplication.translate("Dialog", u"000.000.000-00", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.DdPrincipais), QCoreApplication.translate("Dialog", u"Dados Principais", None))
        self.lineEdit_29.setInputMask("")
        self.lineEdit_32.setInputMask(QCoreApplication.translate("Dialog", u"(##) #####-####", None))
        self.lineEdit_32.setText(QCoreApplication.translate("Dialog", u"() ------", None))
        self.label_28.setText(QCoreApplication.translate("Dialog", u"Dados Complementares :", None))
        self.label_31.setText(QCoreApplication.translate("Dialog", u"Celular:", None))
        self.label_35.setText(QCoreApplication.translate("Dialog", u"E-mail :", None))
        self.label_34.setText(QCoreApplication.translate("Dialog", u"CEP :", None))
        self.label_32.setText(QCoreApplication.translate("Dialog", u"Observa\u00e7\u00e3o :", None))
        self.label_29.setText(QCoreApplication.translate("Dialog", u"N \u00ba :", None))
        self.label_33.setText(QCoreApplication.translate("Dialog", u"Bairro :", None))
        self.label_30.setText(QCoreApplication.translate("Dialog", u"UF :", None))
        self.label_37.setText(QCoreApplication.translate("Dialog", u"Cidade:", None))
        self.label_12.setText(QCoreApplication.translate("Dialog", u"Rua :", None))
        self.lineEdit_26.setInputMask(QCoreApplication.translate("Dialog", u"#####-###", None))
        self.checkBox_5.setText(QCoreApplication.translate("Dialog", u"Possui WhatsApp ?", None))
        self.groupBox_3.setTitle(QCoreApplication.translate("Dialog", u"Op\u00e7\u00f5es", None))
        self.checkBox_4.setText(QCoreApplication.translate("Dialog", u"Adicionar como Cliente", None))
        self.checkBox_6.setText(QCoreApplication.translate("Dialog", u"Adicionar como fornecedor", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.DdAdicionais), QCoreApplication.translate("Dialog", u"Dados Adicionais", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.Permission), QCoreApplication.translate("Dialog", u"Permiss\u00f5es", None))
        self.pushButton_3.setText(QCoreApplication.translate("Dialog", u"&Cancelar", None))
#if QT_CONFIG(shortcut)
        self.pushButton_3.setShortcut(QCoreApplication.translate("Dialog", u"Alt+C", None))
#endif // QT_CONFIG(shortcut)
        self.pushButton_2.setText(QCoreApplication.translate("Dialog", u"A&dicionar", None))
#if QT_CONFIG(shortcut)
        self.pushButton_2.setShortcut(QCoreApplication.translate("Dialog", u"Alt+D", None))
#endif // QT_CONFIG(shortcut)
        self.pushButton.setText(QCoreApplication.translate("Dialog", u"&Alterar", None))
        self.pushButton_4.setText(QCoreApplication.translate("Dialog", u"&Salvar", None))
#if QT_CONFIG(shortcut)
        self.pushButton_4.setShortcut("")
#endif // QT_CONFIG(shortcut)
    # retranslateUi

