# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'CadUser.ui'
##
## Created by: Qt User Interface Compiler version 6.7.3
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QBrush, QColor, QConicalGradient, QCursor,
    QFont, QFontDatabase, QGradient, QIcon,
    QImage, QKeySequence, QLinearGradient, QPainter,
    QPalette, QPixmap, QRadialGradient, QTransform)
from PySide6.QtWidgets import (QAbstractSpinBox, QApplication, QCheckBox, QDateEdit,
    QDialog, QGroupBox, QHBoxLayout, QLCDNumber,
    QLabel, QLayout, QLineEdit, QPlainTextEdit,
    QPushButton, QSizePolicy, QSpacerItem, QTabWidget,
    QWidget)

class Ui_CadUser(object):
    def setupUi(self, CadUser):
        if not CadUser.objectName():
            CadUser.setObjectName(u"CadUser")
        CadUser.resize(762, 611)
        self.tabWidget = QTabWidget(CadUser)
        self.tabWidget.setObjectName(u"tabWidget")
        self.tabWidget.setGeometry(QRect(0, 0, 761, 521))
        font = QFont()
        font.setFamilies([u"Segoe UI"])
        font.setPointSize(12)
        self.tabWidget.setFont(font)
        self.tabWidget.setCursor(QCursor(Qt.CursorShape.PointingHandCursor))
        self.tabWidget.setContextMenuPolicy(Qt.DefaultContextMenu)
        self.tabWidget.setAcceptDrops(False)
        self.tabWidget.setStyleSheet(u"font: 12pt \"Segoe UI\";")
        self.tabWidget.setTabShape(QTabWidget.Triangular)
        self.tabWidget.setElideMode(Qt.ElideLeft)
        self.DdPrincipais = QWidget()
        self.DdPrincipais.setObjectName(u"DdPrincipais")
        self.label = QLabel(self.DdPrincipais)
        self.label.setObjectName(u"label")
        self.label.setGeometry(QRect(20, 50, 131, 16))
        self.text_nome = QLineEdit(self.DdPrincipais)
        self.text_nome.setObjectName(u"text_nome")
        self.text_nome.setGeometry(QRect(20, 70, 591, 21))
        self.label_2 = QLabel(self.DdPrincipais)
        self.label_2.setObjectName(u"label_2")
        self.label_2.setGeometry(QRect(20, 100, 131, 16))
        self.text_email = QLineEdit(self.DdPrincipais)
        self.text_email.setObjectName(u"text_email")
        self.text_email.setGeometry(QRect(20, 120, 591, 21))
        self.label_3 = QLabel(self.DdPrincipais)
        self.label_3.setObjectName(u"label_3")
        self.label_3.setGeometry(QRect(20, 150, 131, 16))
        self.text_phone = QLineEdit(self.DdPrincipais)
        self.text_phone.setObjectName(u"text_phone")
        self.text_phone.setGeometry(QRect(20, 170, 181, 21))
        self.text_phone.setMaxLength(15)
        self.text_phone.setCursorMoveStyle(Qt.VisualMoveStyle)
        self.label_4 = QLabel(self.DdPrincipais)
        self.label_4.setObjectName(u"label_4")
        self.label_4.setGeometry(QRect(220, 150, 151, 16))
        self.dt_nascimento = QDateEdit(self.DdPrincipais)
        self.dt_nascimento.setObjectName(u"dt_nascimento")
        self.dt_nascimento.setGeometry(QRect(220, 170, 151, 22))
        self.dt_nascimento.setWrapping(True)
        self.dt_nascimento.setSpecialValueText(u"")
        self.dt_nascimento.setCorrectionMode(QAbstractSpinBox.CorrectToNearestValue)
        self.dt_nascimento.setKeyboardTracking(False)
        self.dt_nascimento.setProperty(u"showGroupSeparator", True)
        self.dt_nascimento.setCalendarPopup(True)
        self.groupBox = QGroupBox(self.DdPrincipais)
        self.groupBox.setObjectName(u"groupBox")
        self.groupBox.setGeometry(QRect(10, 210, 341, 281))
        self.text_password = QLineEdit(self.groupBox)
        self.text_password.setObjectName(u"text_password")
        self.text_password.setGeometry(QRect(10, 100, 251, 21))
        self.text_password.setEchoMode(QLineEdit.PasswordEchoOnEdit)
        self.text_password.setDragEnabled(False)
        self.text_password.setReadOnly(False)
        self.label_5 = QLabel(self.groupBox)
        self.label_5.setObjectName(u"label_5")
        self.label_5.setGeometry(QRect(10, 30, 131, 16))
        self.text_user = QLineEdit(self.groupBox)
        self.text_user.setObjectName(u"text_user")
        self.text_user.setGeometry(QRect(10, 50, 251, 21))
        self.label_6 = QLabel(self.groupBox)
        self.label_6.setObjectName(u"label_6")
        self.label_6.setGeometry(QRect(10, 80, 131, 16))
        self.groupBox_2 = QGroupBox(self.DdPrincipais)
        self.groupBox_2.setObjectName(u"groupBox_2")
        self.groupBox_2.setGeometry(QRect(360, 210, 331, 281))
        self.check_reset_senha = QCheckBox(self.groupBox_2)
        self.check_reset_senha.setObjectName(u"check_reset_senha")
        self.check_reset_senha.setGeometry(QRect(10, 40, 301, 17))
        self.check_first_acesso = QCheckBox(self.groupBox_2)
        self.check_first_acesso.setObjectName(u"check_first_acesso")
        self.check_first_acesso.setGeometry(QRect(10, 60, 301, 17))
        self.check_first_acesso.setChecked(True)
        self.check_bloqueado = QCheckBox(self.groupBox_2)
        self.check_bloqueado.setObjectName(u"check_bloqueado")
        self.check_bloqueado.setGeometry(QRect(10, 80, 301, 17))
        self.label_7 = QLabel(self.groupBox_2)
        self.label_7.setObjectName(u"label_7")
        self.label_7.setGeometry(QRect(10, 110, 131, 16))
        self.plain_obs = QPlainTextEdit(self.groupBox_2)
        self.plain_obs.setObjectName(u"plain_obs")
        self.plain_obs.setGeometry(QRect(10, 130, 311, 141))
        self.lcd_id = QLCDNumber(self.DdPrincipais)
        self.lcd_id.setObjectName(u"lcd_id")
        self.lcd_id.setGeometry(QRect(20, 10, 91, 23))
        self.label_8 = QLabel(self.DdPrincipais)
        self.label_8.setObjectName(u"label_8")
        self.label_8.setGeometry(QRect(380, 150, 141, 21))
        self.text_cpf = QLineEdit(self.DdPrincipais)
        self.text_cpf.setObjectName(u"text_cpf")
        self.text_cpf.setGeometry(QRect(380, 170, 231, 21))
        self.text_cpf.setCursorPosition(14)
        self.text_cpf.setCursorMoveStyle(Qt.VisualMoveStyle)
        self.check_ativo = QCheckBox(self.DdPrincipais)
        self.check_ativo.setObjectName(u"check_ativo")
        self.check_ativo.setGeometry(QRect(520, 10, 70, 17))
        self.tabWidget.addTab(self.DdPrincipais, "")
        self.DdAdicionais = QWidget()
        self.DdAdicionais.setObjectName(u"DdAdicionais")
        self.text_numero = QLineEdit(self.DdAdicionais)
        self.text_numero.setObjectName(u"text_numero")
        self.text_numero.setGeometry(QRect(520, 30, 121, 21))
        self.text_complementar = QLineEdit(self.DdAdicionais)
        self.text_complementar.setObjectName(u"text_complementar")
        self.text_complementar.setGeometry(QRect(320, 70, 321, 21))
        self.text_uf = QLineEdit(self.DdAdicionais)
        self.text_uf.setObjectName(u"text_uf")
        self.text_uf.setGeometry(QRect(490, 120, 151, 21))
        self.text_uf.setInputMethodHints(Qt.ImhNoAutoUppercase)
        self.text_uf.setMaxLength(2)
        self.text_celular = QLineEdit(self.DdAdicionais)
        self.text_celular.setObjectName(u"text_celular")
        self.text_celular.setGeometry(QRect(10, 180, 181, 21))
        self.text_celular.setMaxLength(15)
        self.text_celular.setCursorMoveStyle(Qt.VisualMoveStyle)
        self.label_28 = QLabel(self.DdAdicionais)
        self.label_28.setObjectName(u"label_28")
        self.label_28.setGeometry(QRect(320, 50, 211, 21))
        self.label_31 = QLabel(self.DdAdicionais)
        self.label_31.setObjectName(u"label_31")
        self.label_31.setGeometry(QRect(10, 160, 131, 16))
        self.label_34 = QLabel(self.DdAdicionais)
        self.label_34.setObjectName(u"label_34")
        self.label_34.setGeometry(QRect(10, 100, 141, 21))
        self.text_rua = QLineEdit(self.DdAdicionais)
        self.text_rua.setObjectName(u"text_rua")
        self.text_rua.setGeometry(QRect(10, 30, 501, 21))
        self.label_32 = QLabel(self.DdAdicionais)
        self.label_32.setObjectName(u"label_32")
        self.label_32.setGeometry(QRect(10, 220, 131, 16))
        self.label_29 = QLabel(self.DdAdicionais)
        self.label_29.setObjectName(u"label_29")
        self.label_29.setGeometry(QRect(520, 10, 141, 21))
        self.text_cidade = QLineEdit(self.DdAdicionais)
        self.text_cidade.setObjectName(u"text_cidade")
        self.text_cidade.setGeometry(QRect(190, 120, 291, 21))
        self.label_33 = QLabel(self.DdAdicionais)
        self.label_33.setObjectName(u"label_33")
        self.label_33.setGeometry(QRect(10, 50, 141, 21))
        self.label_30 = QLabel(self.DdAdicionais)
        self.label_30.setObjectName(u"label_30")
        self.label_30.setGeometry(QRect(490, 100, 141, 21))
        self.label_37 = QLabel(self.DdAdicionais)
        self.label_37.setObjectName(u"label_37")
        self.label_37.setGeometry(QRect(190, 100, 141, 21))
        self.text_bairro = QLineEdit(self.DdAdicionais)
        self.text_bairro.setObjectName(u"text_bairro")
        self.text_bairro.setGeometry(QRect(10, 70, 291, 21))
        self.plain_obs_adicionais = QPlainTextEdit(self.DdAdicionais)
        self.plain_obs_adicionais.setObjectName(u"plain_obs_adicionais")
        self.plain_obs_adicionais.setGeometry(QRect(10, 240, 321, 131))
        self.label_12 = QLabel(self.DdAdicionais)
        self.label_12.setObjectName(u"label_12")
        self.label_12.setGeometry(QRect(10, 10, 141, 21))
        self.text_cep = QLineEdit(self.DdAdicionais)
        self.text_cep.setObjectName(u"text_cep")
        self.text_cep.setGeometry(QRect(10, 120, 161, 21))
        self.check_whats = QCheckBox(self.DdAdicionais)
        self.check_whats.setObjectName(u"check_whats")
        self.check_whats.setGeometry(QRect(210, 180, 151, 17))
        self.check_whats.setChecked(False)
        self.groupBox_3 = QGroupBox(self.DdAdicionais)
        self.groupBox_3.setObjectName(u"groupBox_3")
        self.groupBox_3.setGeometry(QRect(380, 160, 261, 251))
        self.check_add_cliente = QCheckBox(self.groupBox_3)
        self.check_add_cliente.setObjectName(u"check_add_cliente")
        self.check_add_cliente.setGeometry(QRect(20, 30, 201, 17))
        self.check_add_fornecedor = QCheckBox(self.groupBox_3)
        self.check_add_fornecedor.setObjectName(u"check_add_fornecedor")
        self.check_add_fornecedor.setGeometry(QRect(20, 50, 221, 17))
        self.tabWidget.addTab(self.DdAdicionais, "")
        self.Permission = QWidget()
        self.Permission.setObjectName(u"Permission")
        self.tabWidget.addTab(self.Permission, "")
        self.layoutWidget = QWidget(CadUser)
        self.layoutWidget.setObjectName(u"layoutWidget")
        self.layoutWidget.setGeometry(QRect(370, 530, 366, 25))
        self.horizontalLayout_3 = QHBoxLayout(self.layoutWidget)
        self.horizontalLayout_3.setObjectName(u"horizontalLayout_3")
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.bnt_back_full = QPushButton(self.layoutWidget)
        self.bnt_back_full.setObjectName(u"bnt_back_full")

        self.horizontalLayout_3.addWidget(self.bnt_back_full)

        self.bnt_back = QPushButton(self.layoutWidget)
        self.bnt_back.setObjectName(u"bnt_back")

        self.horizontalLayout_3.addWidget(self.bnt_back)

        self.horizontalSpacer_2 = QSpacerItem(20, 20, QSizePolicy.Policy.Minimum, QSizePolicy.Policy.Minimum)

        self.horizontalLayout_3.addItem(self.horizontalSpacer_2)

        self.bnt_next = QPushButton(self.layoutWidget)
        self.bnt_next.setObjectName(u"bnt_next")

        self.horizontalLayout_3.addWidget(self.bnt_next)

        self.bnt_next_full = QPushButton(self.layoutWidget)
        self.bnt_next_full.setObjectName(u"bnt_next_full")

        self.horizontalLayout_3.addWidget(self.bnt_next_full)

        self.layoutWidget_2 = QWidget(CadUser)
        self.layoutWidget_2.setObjectName(u"layoutWidget_2")
        self.layoutWidget_2.setGeometry(QRect(15, 570, 721, 32))
        self.horizontalLayout = QHBoxLayout(self.layoutWidget_2)
        self.horizontalLayout.setSpacing(6)
        self.horizontalLayout.setObjectName(u"horizontalLayout")
        self.horizontalLayout.setSizeConstraint(QLayout.SetDefaultConstraint)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.bnt_alterar = QPushButton(self.layoutWidget_2)
        self.bnt_alterar.setObjectName(u"bnt_alterar")
        self.bnt_alterar.setMinimumSize(QSize(100, 30))
        self.bnt_alterar.setMaximumSize(QSize(131, 41))

        self.horizontalLayout.addWidget(self.bnt_alterar)

        self.horizontalSpacer = QSpacerItem(58, 20, QSizePolicy.Policy.Expanding, QSizePolicy.Policy.Minimum)

        self.horizontalLayout.addItem(self.horizontalSpacer)

        self.bnt_adicionar = QPushButton(self.layoutWidget_2)
        self.bnt_adicionar.setObjectName(u"bnt_adicionar")
        self.bnt_adicionar.setEnabled(True)
        self.bnt_adicionar.setMinimumSize(QSize(100, 0))
        self.bnt_adicionar.setMaximumSize(QSize(131, 41))

        self.horizontalLayout.addWidget(self.bnt_adicionar)

        self.bnt_salvar = QPushButton(self.layoutWidget_2)
        self.bnt_salvar.setObjectName(u"bnt_salvar")
        self.bnt_salvar.setEnabled(False)
        self.bnt_salvar.setMinimumSize(QSize(100, 0))
        self.bnt_salvar.setMaximumSize(QSize(131, 41))

        self.horizontalLayout.addWidget(self.bnt_salvar)

        self.bnt_search = QPushButton(self.layoutWidget_2)
        self.bnt_search.setObjectName(u"bnt_search")
        self.bnt_search.setMinimumSize(QSize(100, 0))
        self.bnt_search.setMaximumSize(QSize(131, 41))
        self.bnt_search.setCheckable(False)
        self.bnt_search.setChecked(False)
        self.bnt_search.setAutoRepeat(False)

        self.horizontalLayout.addWidget(self.bnt_search)

        self.bnt_excluir = QPushButton(self.layoutWidget_2)
        self.bnt_excluir.setObjectName(u"bnt_excluir")
        self.bnt_excluir.setMinimumSize(QSize(100, 0))
        self.bnt_excluir.setMaximumSize(QSize(131, 41))
        self.bnt_excluir.setCheckable(False)
        self.bnt_excluir.setChecked(False)
        self.bnt_excluir.setAutoRepeat(False)

        self.horizontalLayout.addWidget(self.bnt_excluir)

        self.bnt_cancelar = QPushButton(self.layoutWidget_2)
        self.bnt_cancelar.setObjectName(u"bnt_cancelar")
        self.bnt_cancelar.setMinimumSize(QSize(100, 0))
        self.bnt_cancelar.setMaximumSize(QSize(131, 41))
        self.bnt_cancelar.setCheckable(False)
        self.bnt_cancelar.setChecked(False)
        self.bnt_cancelar.setAutoRepeat(False)

        self.horizontalLayout.addWidget(self.bnt_cancelar)


        self.retranslateUi(CadUser)

        self.tabWidget.setCurrentIndex(0)


        QMetaObject.connectSlotsByName(CadUser)
    # setupUi

    def retranslateUi(self, CadUser):
        CadUser.setWindowTitle(QCoreApplication.translate("CadUser", u"Dialog", None))
        self.label.setText(QCoreApplication.translate("CadUser", u"Nome Completo:", None))
        self.text_nome.setInputMask("")
        self.label_2.setText(QCoreApplication.translate("CadUser", u"E-mail :", None))
        self.text_email.setInputMask("")
        self.label_3.setText(QCoreApplication.translate("CadUser", u"Telefone :", None))
        self.text_phone.setInputMask(QCoreApplication.translate("CadUser", u"(##) #####-####", None))
        self.text_phone.setText(QCoreApplication.translate("CadUser", u"() ------", None))
        self.label_4.setText(QCoreApplication.translate("CadUser", u"Data de Nascimento:", None))
        self.groupBox.setTitle(QCoreApplication.translate("CadUser", u"Configura\u00e7\u00f5es de usu\u00e1rio", None))
        self.text_password.setInputMask("")
        self.text_password.setText("")
        self.label_5.setText(QCoreApplication.translate("CadUser", u"Usu\u00e1rio :", None))
        self.text_user.setInputMask("")
        self.text_user.setText("")
        self.label_6.setText(QCoreApplication.translate("CadUser", u"Senha :", None))
        self.groupBox_2.setTitle(QCoreApplication.translate("CadUser", u"Op\u00e7\u00f5es de Usu\u00e1rio :", None))
        self.check_reset_senha.setText(QCoreApplication.translate("CadUser", u"Resetar Senha", None))
        self.check_first_acesso.setText(QCoreApplication.translate("CadUser", u"Primeiro Acesso", None))
        self.check_bloqueado.setText(QCoreApplication.translate("CadUser", u"Bloqueado", None))
        self.label_7.setText(QCoreApplication.translate("CadUser", u"Observa\u00e7\u00f5es:", None))
        self.label_8.setText(QCoreApplication.translate("CadUser", u"CPF :", None))
        self.text_cpf.setInputMask(QCoreApplication.translate("CadUser", u"###.###.###-##", None))
        self.text_cpf.setText(QCoreApplication.translate("CadUser", u"000.000.000-00", None))
        self.check_ativo.setText(QCoreApplication.translate("CadUser", u"Ativo", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.DdPrincipais), QCoreApplication.translate("CadUser", u"Dados Principais", None))
        self.text_celular.setInputMask(QCoreApplication.translate("CadUser", u"(##) #####-####", None))
        self.text_celular.setText(QCoreApplication.translate("CadUser", u"() ------", None))
        self.label_28.setText(QCoreApplication.translate("CadUser", u"Dados Complementares :", None))
        self.label_31.setText(QCoreApplication.translate("CadUser", u"Celular:", None))
        self.label_34.setText(QCoreApplication.translate("CadUser", u"CEP :", None))
        self.label_32.setText(QCoreApplication.translate("CadUser", u"Observa\u00e7\u00e3o :", None))
        self.label_29.setText(QCoreApplication.translate("CadUser", u"N \u00ba :", None))
        self.label_33.setText(QCoreApplication.translate("CadUser", u"Bairro :", None))
        self.label_30.setText(QCoreApplication.translate("CadUser", u"UF :", None))
        self.label_37.setText(QCoreApplication.translate("CadUser", u"Cidade:", None))
        self.label_12.setText(QCoreApplication.translate("CadUser", u"Rua :", None))
        self.text_cep.setInputMask(QCoreApplication.translate("CadUser", u"#####-###", None))
        self.check_whats.setText(QCoreApplication.translate("CadUser", u"Possui WhatsApp ?", None))
        self.groupBox_3.setTitle(QCoreApplication.translate("CadUser", u"Op\u00e7\u00f5es", None))
        self.check_add_cliente.setText(QCoreApplication.translate("CadUser", u"Adicionar como Cliente", None))
        self.check_add_fornecedor.setText(QCoreApplication.translate("CadUser", u"Adicionar como fornecedor", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.DdAdicionais), QCoreApplication.translate("CadUser", u"Dados Adicionais", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.Permission), QCoreApplication.translate("CadUser", u"Permiss\u00f5es", None))
#if QT_CONFIG(tooltip)
        self.bnt_back_full.setToolTip(QCoreApplication.translate("CadUser", u"<html><head/><body><p>Ir para o primeiro...</p></body></html>", None))
#endif // QT_CONFIG(tooltip)
        self.bnt_back_full.setText(QCoreApplication.translate("CadUser", u"<<", None))
#if QT_CONFIG(tooltip)
        self.bnt_back.setToolTip(QCoreApplication.translate("CadUser", u"<html><head/><body><p>Voltar...</p></body></html>", None))
#endif // QT_CONFIG(tooltip)
        self.bnt_back.setText(QCoreApplication.translate("CadUser", u"<", None))
#if QT_CONFIG(tooltip)
        self.bnt_next.setToolTip(QCoreApplication.translate("CadUser", u"<html><head/><body><p>Pr\u00f3ximo...</p></body></html>", None))
#endif // QT_CONFIG(tooltip)
        self.bnt_next.setText(QCoreApplication.translate("CadUser", u">", None))
#if QT_CONFIG(tooltip)
        self.bnt_next_full.setToolTip(QCoreApplication.translate("CadUser", u"<html><head/><body><p><span style=\" font-weight:600;\">Ir para o fim.</span></p></body></html>", None))
#endif // QT_CONFIG(tooltip)
        self.bnt_next_full.setText(QCoreApplication.translate("CadUser", u">>", None))
        self.bnt_alterar.setText(QCoreApplication.translate("CadUser", u"&Alterar", None))
        self.bnt_adicionar.setText(QCoreApplication.translate("CadUser", u"&Incluir", None))
#if QT_CONFIG(shortcut)
        self.bnt_adicionar.setShortcut(QCoreApplication.translate("CadUser", u"Alt+I", None))
#endif // QT_CONFIG(shortcut)
        self.bnt_salvar.setText(QCoreApplication.translate("CadUser", u"&Salvar", None))
#if QT_CONFIG(shortcut)
        self.bnt_salvar.setShortcut("")
#endif // QT_CONFIG(shortcut)
        self.bnt_search.setText(QCoreApplication.translate("CadUser", u"&Pesquisar", None))
#if QT_CONFIG(shortcut)
        self.bnt_search.setShortcut(QCoreApplication.translate("CadUser", u"Alt+P", None))
#endif // QT_CONFIG(shortcut)
        self.bnt_excluir.setText(QCoreApplication.translate("CadUser", u"&Excluir", None))
#if QT_CONFIG(shortcut)
        self.bnt_excluir.setShortcut(QCoreApplication.translate("CadUser", u"Alt+E", None))
#endif // QT_CONFIG(shortcut)
        self.bnt_cancelar.setText(QCoreApplication.translate("CadUser", u"&Cancelar", None))
#if QT_CONFIG(shortcut)
        self.bnt_cancelar.setShortcut(QCoreApplication.translate("CadUser", u"Alt+C", None))
#endif // QT_CONFIG(shortcut)
    # retranslateUi

