# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'MainWindow.ui'
##
## Created by: Qt User Interface Compiler version 6.7.3
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QAction, QBrush, QColor, QConicalGradient,
    QCursor, QFont, QFontDatabase, QGradient,
    QIcon, QImage, QKeySequence, QLinearGradient,
    QPainter, QPalette, QPixmap, QRadialGradient,
    QTransform)
from PySide6.QtWidgets import (QApplication, QFrame, QHBoxLayout, QLabel,
    QMainWindow, QMenu, QMenuBar, QPushButton,
    QSizePolicy, QTabWidget, QVBoxLayout, QWidget)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        if not MainWindow.objectName():
            MainWindow.setObjectName(u"MainWindow")
        MainWindow.setWindowModality(Qt.NonModal)
        MainWindow.resize(931, 683)
        MainWindow.setToolButtonStyle(Qt.ToolButtonIconOnly)
        MainWindow.setTabShape(QTabWidget.Rounded)
        MainWindow.setUnifiedTitleAndToolBarOnMac(False)
        self.actionReceitas = QAction(MainWindow)
        self.actionReceitas.setObjectName(u"actionReceitas")
        self.actionInvestimentos = QAction(MainWindow)
        self.actionInvestimentos.setObjectName(u"actionInvestimentos")
        self.actionDespesa_Fixas = QAction(MainWindow)
        self.actionDespesa_Fixas.setObjectName(u"actionDespesa_Fixas")
        self.actionDespesa_Correntes = QAction(MainWindow)
        self.actionDespesa_Correntes.setObjectName(u"actionDespesa_Correntes")
        self.actionDespesas_Avulsas = QAction(MainWindow)
        self.actionDespesas_Avulsas.setObjectName(u"actionDespesas_Avulsas")
        self.actionMovimenta_o = QAction(MainWindow)
        self.actionMovimenta_o.setObjectName(u"actionMovimenta_o")
        self.actionRelat_rios = QAction(MainWindow)
        self.actionRelat_rios.setObjectName(u"actionRelat_rios")
        self.actionDespesa_Fixas_2 = QAction(MainWindow)
        self.actionDespesa_Fixas_2.setObjectName(u"actionDespesa_Fixas_2")
        self.actionDespesa_Corrente = QAction(MainWindow)
        self.actionDespesa_Corrente.setObjectName(u"actionDespesa_Corrente")
        self.actionMovimenta_es = QAction(MainWindow)
        self.actionMovimenta_es.setObjectName(u"actionMovimenta_es")
        self.actionReceitas_Fixas = QAction(MainWindow)
        self.actionReceitas_Fixas.setObjectName(u"actionReceitas_Fixas")
        self.actionReceitas_Correntes = QAction(MainWindow)
        self.actionReceitas_Correntes.setObjectName(u"actionReceitas_Correntes")
        self.actionRelat_rios_2 = QAction(MainWindow)
        self.actionRelat_rios_2.setObjectName(u"actionRelat_rios_2")
        self.actionLan_amento_2 = QAction(MainWindow)
        self.actionLan_amento_2.setObjectName(u"actionLan_amento_2")
        self.actionMovimenta_es_2 = QAction(MainWindow)
        self.actionMovimenta_es_2.setObjectName(u"actionMovimenta_es_2")
        self.actionRelat_rios_3 = QAction(MainWindow)
        self.actionRelat_rios_3.setObjectName(u"actionRelat_rios_3")
        self.actionMovimenta_es_3 = QAction(MainWindow)
        self.actionMovimenta_es_3.setObjectName(u"actionMovimenta_es_3")
        self.actionRelat_rios_4 = QAction(MainWindow)
        self.actionRelat_rios_4.setObjectName(u"actionRelat_rios_4")
        self.actionInvent_rio = QAction(MainWindow)
        self.actionInvent_rio.setObjectName(u"actionInvent_rio")
        self.actionAdd_item = QAction(MainWindow)
        self.actionAdd_item.setObjectName(u"actionAdd_item")
        self.actionBaixa_de_Estoque = QAction(MainWindow)
        self.actionBaixa_de_Estoque.setObjectName(u"actionBaixa_de_Estoque")
        self.actionOrigens = QAction(MainWindow)
        self.actionOrigens.setObjectName(u"actionOrigens")
        self.actionProdutos_itens = QAction(MainWindow)
        self.actionProdutos_itens.setObjectName(u"actionProdutos_itens")
        self.actionCategoria = QAction(MainWindow)
        self.actionCategoria.setObjectName(u"actionCategoria")
        self.actionCategoria_2 = QAction(MainWindow)
        self.actionCategoria_2.setObjectName(u"actionCategoria_2")
        self.actionClasse = QAction(MainWindow)
        self.actionClasse.setObjectName(u"actionClasse")
        self.actionEmpresa = QAction(MainWindow)
        self.actionEmpresa.setObjectName(u"actionEmpresa")
        self.actionInstitui_es = QAction(MainWindow)
        self.actionInstitui_es.setObjectName(u"actionInstitui_es")
        self.actionAg_ncia = QAction(MainWindow)
        self.actionAg_ncia.setObjectName(u"actionAg_ncia")
        self.actionAg_ncia_2 = QAction(MainWindow)
        self.actionAg_ncia_2.setObjectName(u"actionAg_ncia_2")
        self.actionConta = QAction(MainWindow)
        self.actionConta.setObjectName(u"actionConta")
        self.actionUsu_rio = QAction(MainWindow)
        self.actionUsu_rio.setObjectName(u"actionUsu_rio")
        self.actionGrupo = QAction(MainWindow)
        self.actionGrupo.setObjectName(u"actionGrupo")
        self.actionFornecedor = QAction(MainWindow)
        self.actionFornecedor.setObjectName(u"actionFornecedor")
        self.actionOrigem = QAction(MainWindow)
        self.actionOrigem.setObjectName(u"actionOrigem")
        self.actionCategoria_3 = QAction(MainWindow)
        self.actionCategoria_3.setObjectName(u"actionCategoria_3")
        self.actionOrigem_2 = QAction(MainWindow)
        self.actionOrigem_2.setObjectName(u"actionOrigem_2")
        self.actionCategoria_4 = QAction(MainWindow)
        self.actionCategoria_4.setObjectName(u"actionCategoria_4")
        self.actionMovimenta_o_2 = QAction(MainWindow)
        self.actionMovimenta_o_2.setObjectName(u"actionMovimenta_o_2")
        self.centralwidget = QWidget(MainWindow)
        self.centralwidget.setObjectName(u"centralwidget")
        self.verticalLayout = QVBoxLayout(self.centralwidget)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName(u"verticalLayout")
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.frmTop = QFrame(self.centralwidget)
        self.frmTop.setObjectName(u"frmTop")
        self.frmTop.setMinimumSize(QSize(931, 41))
        self.frmTop.setMaximumSize(QSize(16777215, 41))
        font = QFont()
        font.setFamilies([u"Segoe UI Black"])
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        self.frmTop.setFont(font)
        self.frmTop.setStyleSheet(u"font: 87 12pt \"Segoe UI Black\";")
        self.frmTop.setFrameShape(QFrame.Panel)
        self.frmTop.setFrameShadow(QFrame.Raised)
        self.widget = QWidget(self.frmTop)
        self.widget.setObjectName(u"widget")
        self.widget.setGeometry(QRect(10, 10, 126, 23))
        self.horizontalLayout = QHBoxLayout(self.widget)
        self.horizontalLayout.setObjectName(u"horizontalLayout")
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.label = QLabel(self.widget)
        self.label.setObjectName(u"label")

        self.horizontalLayout.addWidget(self.label)

        self.label_2 = QLabel(self.widget)
        self.label_2.setObjectName(u"label_2")

        self.horizontalLayout.addWidget(self.label_2)


        self.verticalLayout.addWidget(self.frmTop)

        self.frmLeft = QFrame(self.centralwidget)
        self.frmLeft.setObjectName(u"frmLeft")
        self.frmLeft.setMinimumSize(QSize(131, 621))
        self.frmLeft.setMaximumSize(QSize(161, 16777215))
        self.frmLeft.setStyleSheet(u"font: 87 12pt \"Segoe UI Black\";")
        self.frmLeft.setFrameShape(QFrame.Panel)
        self.frmLeft.setFrameShadow(QFrame.Raised)
        self.widget1 = QWidget(self.frmLeft)
        self.widget1.setObjectName(u"widget1")
        self.widget1.setGeometry(QRect(10, 111, 103, 197))
        self.verticalLayout_2 = QVBoxLayout(self.widget1)
        self.verticalLayout_2.setObjectName(u"verticalLayout_2")
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.pushButton = QPushButton(self.widget1)
        self.pushButton.setObjectName(u"pushButton")
        self.pushButton.setMinimumSize(QSize(101, 61))
        self.pushButton.setMaximumSize(QSize(101, 61))

        self.verticalLayout_2.addWidget(self.pushButton)

        self.pushButton_2 = QPushButton(self.widget1)
        self.pushButton_2.setObjectName(u"pushButton_2")
        self.pushButton_2.setMinimumSize(QSize(101, 61))
        self.pushButton_2.setMaximumSize(QSize(101, 61))

        self.verticalLayout_2.addWidget(self.pushButton_2)

        self.pushButton_3 = QPushButton(self.widget1)
        self.pushButton_3.setObjectName(u"pushButton_3")
        self.pushButton_3.setMinimumSize(QSize(101, 61))
        self.pushButton_3.setMaximumSize(QSize(101, 61))

        self.verticalLayout_2.addWidget(self.pushButton_3)


        self.verticalLayout.addWidget(self.frmLeft)

        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QMenuBar(MainWindow)
        self.menubar.setObjectName(u"menubar")
        self.menubar.setGeometry(QRect(0, 0, 931, 21))
        self.menuSistema = QMenu(self.menubar)
        self.menuSistema.setObjectName(u"menuSistema")
        self.menuCadastro = QMenu(self.menubar)
        self.menuCadastro.setObjectName(u"menuCadastro")
        self.menuProdutos_Itens = QMenu(self.menuCadastro)
        self.menuProdutos_Itens.setObjectName(u"menuProdutos_Itens")
        self.menuAuxiliares = QMenu(self.menuCadastro)
        self.menuAuxiliares.setObjectName(u"menuAuxiliares")
        self.menuBancos = QMenu(self.menuAuxiliares)
        self.menuBancos.setObjectName(u"menuBancos")
        self.menuDespesa_2 = QMenu(self.menuAuxiliares)
        self.menuDespesa_2.setObjectName(u"menuDespesa_2")
        self.menuReceita = QMenu(self.menuAuxiliares)
        self.menuReceita.setObjectName(u"menuReceita")
        self.menuConta_Corrente = QMenu(self.menuCadastro)
        self.menuConta_Corrente.setObjectName(u"menuConta_Corrente")
        self.menuUsu_rios = QMenu(self.menuCadastro)
        self.menuUsu_rios.setObjectName(u"menuUsu_rios")
        self.menuDespesa = QMenu(self.menubar)
        self.menuDespesa.setObjectName(u"menuDespesa")
        self.menuLan_amento = QMenu(self.menuDespesa)
        self.menuLan_amento.setObjectName(u"menuLan_amento")
        self.menuConfiguracoes = QMenu(self.menubar)
        self.menuConfiguracoes.setObjectName(u"menuConfiguracoes")
        self.menuRelatorios = QMenu(self.menubar)
        self.menuRelatorios.setObjectName(u"menuRelatorios")
        self.menuReceitas = QMenu(self.menubar)
        self.menuReceitas.setObjectName(u"menuReceitas")
        self.menuLan_amentos = QMenu(self.menuReceitas)
        self.menuLan_amentos.setObjectName(u"menuLan_amentos")
        self.menuInvestimento = QMenu(self.menubar)
        self.menuInvestimento.setObjectName(u"menuInvestimento")
        self.menuEstoque = QMenu(self.menubar)
        self.menuEstoque.setObjectName(u"menuEstoque")
        self.menuLan_amento_2 = QMenu(self.menuEstoque)
        self.menuLan_amento_2.setObjectName(u"menuLan_amento_2")
        self.menuFinanceiro = QMenu(self.menubar)
        self.menuFinanceiro.setObjectName(u"menuFinanceiro")
        MainWindow.setMenuBar(self.menubar)

        self.menubar.addAction(self.menuSistema.menuAction())
        self.menubar.addAction(self.menuCadastro.menuAction())
        self.menubar.addAction(self.menuDespesa.menuAction())
        self.menubar.addAction(self.menuReceitas.menuAction())
        self.menubar.addAction(self.menuFinanceiro.menuAction())
        self.menubar.addAction(self.menuInvestimento.menuAction())
        self.menubar.addAction(self.menuEstoque.menuAction())
        self.menubar.addAction(self.menuRelatorios.menuAction())
        self.menubar.addAction(self.menuConfiguracoes.menuAction())
        self.menuSistema.addAction(self.actionEmpresa)
        self.menuCadastro.addAction(self.menuProdutos_Itens.menuAction())
        self.menuCadastro.addAction(self.actionFornecedor)
        self.menuCadastro.addAction(self.menuUsu_rios.menuAction())
        self.menuCadastro.addAction(self.menuConta_Corrente.menuAction())
        self.menuCadastro.addSeparator()
        self.menuCadastro.addAction(self.menuAuxiliares.menuAction())
        self.menuProdutos_Itens.addAction(self.actionProdutos_itens)
        self.menuProdutos_Itens.addAction(self.actionCategoria_2)
        self.menuProdutos_Itens.addAction(self.actionClasse)
        self.menuAuxiliares.addAction(self.menuBancos.menuAction())
        self.menuAuxiliares.addAction(self.menuDespesa_2.menuAction())
        self.menuAuxiliares.addAction(self.menuReceita.menuAction())
        self.menuBancos.addAction(self.actionInstitui_es)
        self.menuBancos.addAction(self.actionAg_ncia)
        self.menuDespesa_2.addAction(self.actionOrigem)
        self.menuDespesa_2.addAction(self.actionCategoria_3)
        self.menuReceita.addAction(self.actionOrigem_2)
        self.menuReceita.addAction(self.actionCategoria_4)
        self.menuConta_Corrente.addAction(self.actionAg_ncia_2)
        self.menuConta_Corrente.addAction(self.actionConta)
        self.menuUsu_rios.addAction(self.actionUsu_rio)
        self.menuUsu_rios.addAction(self.actionGrupo)
        self.menuDespesa.addAction(self.menuLan_amento.menuAction())
        self.menuDespesa.addSeparator()
        self.menuDespesa.addAction(self.actionRelat_rios)
        self.menuLan_amento.addAction(self.actionDespesa_Fixas_2)
        self.menuLan_amento.addAction(self.actionDespesa_Corrente)
        self.menuReceitas.addAction(self.menuLan_amentos.menuAction())
        self.menuReceitas.addSeparator()
        self.menuReceitas.addAction(self.actionRelat_rios_2)
        self.menuLan_amentos.addAction(self.actionReceitas_Fixas)
        self.menuLan_amentos.addAction(self.actionReceitas_Correntes)
        self.menuInvestimento.addAction(self.actionLan_amento_2)
        self.menuInvestimento.addAction(self.actionMovimenta_es_2)
        self.menuInvestimento.addSeparator()
        self.menuInvestimento.addAction(self.actionRelat_rios_3)
        self.menuEstoque.addAction(self.menuLan_amento_2.menuAction())
        self.menuEstoque.addAction(self.actionMovimenta_es_3)
        self.menuEstoque.addAction(self.actionInvent_rio)
        self.menuEstoque.addSeparator()
        self.menuEstoque.addAction(self.actionRelat_rios_4)
        self.menuLan_amento_2.addAction(self.actionAdd_item)
        self.menuLan_amento_2.addAction(self.actionBaixa_de_Estoque)
        self.menuFinanceiro.addAction(self.actionMovimenta_o_2)

        self.retranslateUi(MainWindow)

        QMetaObject.connectSlotsByName(MainWindow)
    # setupUi

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QCoreApplication.translate("MainWindow", u"MainWindow", None))
        self.actionReceitas.setText(QCoreApplication.translate("MainWindow", u"Receitas", None))
        self.actionInvestimentos.setText(QCoreApplication.translate("MainWindow", u"Investimentos", None))
        self.actionDespesa_Fixas.setText(QCoreApplication.translate("MainWindow", u"Despesa Fixas", None))
        self.actionDespesa_Correntes.setText(QCoreApplication.translate("MainWindow", u"Despesa Correntes", None))
        self.actionDespesas_Avulsas.setText(QCoreApplication.translate("MainWindow", u"Despesas Avulsas", None))
        self.actionMovimenta_o.setText(QCoreApplication.translate("MainWindow", u"Movimenta\u00e7\u00e3o", None))
        self.actionRelat_rios.setText(QCoreApplication.translate("MainWindow", u"Relat\u00f3rios", None))
        self.actionDespesa_Fixas_2.setText(QCoreApplication.translate("MainWindow", u"Despesa Fixa", None))
        self.actionDespesa_Corrente.setText(QCoreApplication.translate("MainWindow", u"Despesa Corrente", None))
        self.actionMovimenta_es.setText(QCoreApplication.translate("MainWindow", u"Movimenta\u00e7\u00f5es", None))
        self.actionReceitas_Fixas.setText(QCoreApplication.translate("MainWindow", u"Receitas Fixas", None))
        self.actionReceitas_Correntes.setText(QCoreApplication.translate("MainWindow", u"Receitas Correntes", None))
        self.actionRelat_rios_2.setText(QCoreApplication.translate("MainWindow", u"Relat\u00f3rios", None))
        self.actionLan_amento_2.setText(QCoreApplication.translate("MainWindow", u"Lan\u00e7amento", None))
        self.actionMovimenta_es_2.setText(QCoreApplication.translate("MainWindow", u"Movimenta\u00e7\u00f5es", None))
        self.actionRelat_rios_3.setText(QCoreApplication.translate("MainWindow", u"Relat\u00f3rios", None))
        self.actionMovimenta_es_3.setText(QCoreApplication.translate("MainWindow", u"Movimenta\u00e7\u00f5es", None))
        self.actionRelat_rios_4.setText(QCoreApplication.translate("MainWindow", u"Relat\u00f3rios", None))
        self.actionInvent_rio.setText(QCoreApplication.translate("MainWindow", u"Invent\u00e1rio", None))
        self.actionAdd_item.setText(QCoreApplication.translate("MainWindow", u"Add item ", None))
        self.actionBaixa_de_Estoque.setText(QCoreApplication.translate("MainWindow", u"Baixa de Estoque", None))
        self.actionOrigens.setText(QCoreApplication.translate("MainWindow", u"Origens", None))
        self.actionProdutos_itens.setText(QCoreApplication.translate("MainWindow", u"Produtos/itens", None))
        self.actionCategoria.setText(QCoreApplication.translate("MainWindow", u"Categoria", None))
        self.actionCategoria_2.setText(QCoreApplication.translate("MainWindow", u"Categoria", None))
        self.actionClasse.setText(QCoreApplication.translate("MainWindow", u"Classe ", None))
        self.actionEmpresa.setText(QCoreApplication.translate("MainWindow", u"Empresa", None))
        self.actionInstitui_es.setText(QCoreApplication.translate("MainWindow", u"Institui\u00e7\u00f5es", None))
        self.actionAg_ncia.setText(QCoreApplication.translate("MainWindow", u"Ag\u00eancia", None))
        self.actionAg_ncia_2.setText(QCoreApplication.translate("MainWindow", u"Ag\u00eancia", None))
        self.actionConta.setText(QCoreApplication.translate("MainWindow", u"Conta ", None))
        self.actionUsu_rio.setText(QCoreApplication.translate("MainWindow", u"Usu\u00e1rio", None))
        self.actionGrupo.setText(QCoreApplication.translate("MainWindow", u"Grupo de usu\u00e1rios", None))
        self.actionFornecedor.setText(QCoreApplication.translate("MainWindow", u"Fornecedor", None))
        self.actionOrigem.setText(QCoreApplication.translate("MainWindow", u"Origem ", None))
        self.actionCategoria_3.setText(QCoreApplication.translate("MainWindow", u"Categoria ", None))
        self.actionOrigem_2.setText(QCoreApplication.translate("MainWindow", u"Origem", None))
        self.actionCategoria_4.setText(QCoreApplication.translate("MainWindow", u"Categoria", None))
        self.actionMovimenta_o_2.setText(QCoreApplication.translate("MainWindow", u"Movimenta\u00e7\u00e3o", None))
        self.label.setText(QCoreApplication.translate("MainWindow", u"Usu\u00e1rio:", None))
        self.label_2.setText(QCoreApplication.translate("MainWindow", u"Admin", None))
        self.pushButton.setText(QCoreApplication.translate("MainWindow", u"Receitas", None))
        self.pushButton_2.setText(QCoreApplication.translate("MainWindow", u"Despesas", None))
        self.pushButton_3.setText(QCoreApplication.translate("MainWindow", u"Estoque", None))
        self.menuSistema.setTitle(QCoreApplication.translate("MainWindow", u"Sistema", None))
        self.menuCadastro.setTitle(QCoreApplication.translate("MainWindow", u"Cadastro", None))
        self.menuProdutos_Itens.setTitle(QCoreApplication.translate("MainWindow", u"Produtos/Itens", None))
        self.menuAuxiliares.setTitle(QCoreApplication.translate("MainWindow", u"Auxiliares", None))
        self.menuBancos.setTitle(QCoreApplication.translate("MainWindow", u"Bancos", None))
        self.menuDespesa_2.setTitle(QCoreApplication.translate("MainWindow", u"Despesa", None))
        self.menuReceita.setTitle(QCoreApplication.translate("MainWindow", u"Receita", None))
        self.menuConta_Corrente.setTitle(QCoreApplication.translate("MainWindow", u"Conta Corrente", None))
        self.menuUsu_rios.setTitle(QCoreApplication.translate("MainWindow", u"Usu\u00e1rios", None))
        self.menuDespesa.setTitle(QCoreApplication.translate("MainWindow", u"Despesas", None))
        self.menuLan_amento.setTitle(QCoreApplication.translate("MainWindow", u"Lan\u00e7amento", None))
        self.menuConfiguracoes.setTitle(QCoreApplication.translate("MainWindow", u"Configura\u00e7\u00f5es", None))
        self.menuRelatorios.setTitle(QCoreApplication.translate("MainWindow", u"Relat\u00f3rios", None))
        self.menuReceitas.setTitle(QCoreApplication.translate("MainWindow", u"Receitas", None))
        self.menuLan_amentos.setTitle(QCoreApplication.translate("MainWindow", u"Lan\u00e7amentos", None))
        self.menuInvestimento.setTitle(QCoreApplication.translate("MainWindow", u"Investimento", None))
        self.menuEstoque.setTitle(QCoreApplication.translate("MainWindow", u"Estoque", None))
        self.menuLan_amento_2.setTitle(QCoreApplication.translate("MainWindow", u"Lan\u00e7amento", None))
        self.menuFinanceiro.setTitle(QCoreApplication.translate("MainWindow", u"Financeiro", None))
    # retranslateUi

