# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'MainWindow.ui'
##
## Created by: Qt User Interface Compiler version 6.7.3
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QAction, QBrush, QColor, QConicalGradient,
    QCursor, QFont, QFontDatabase, QGradient,
    QIcon, QImage, QKeySequence, QLinearGradient,
    QPainter, QPalette, QPixmap, QRadialGradient,
    QTransform)
from PySide6.QtWidgets import (QAbstractScrollArea, QApplication, QFrame, QHBoxLayout,
    QLabel, QMainWindow, QMdiArea, QMenu,
    QMenuBar, QPushButton, QSizePolicy, QSpacerItem,
    QTabWidget, QVBoxLayout, QWidget)
import icons_rc

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        if not MainWindow.objectName():
            MainWindow.setObjectName(u"MainWindow")
        MainWindow.setWindowModality(Qt.NonModal)
        MainWindow.resize(1232, 716)
        MainWindow.setToolButtonStyle(Qt.ToolButtonIconOnly)
        MainWindow.setTabShape(QTabWidget.Rounded)
        MainWindow.setUnifiedTitleAndToolBarOnMac(False)
        self.actionReceitas = QAction(MainWindow)
        self.actionReceitas.setObjectName(u"actionReceitas")
        self.actionInvestimentos = QAction(MainWindow)
        self.actionInvestimentos.setObjectName(u"actionInvestimentos")
        self.actionDespesa_Fixas = QAction(MainWindow)
        self.actionDespesa_Fixas.setObjectName(u"actionDespesa_Fixas")
        self.actionDespesa_Correntes = QAction(MainWindow)
        self.actionDespesa_Correntes.setObjectName(u"actionDespesa_Correntes")
        self.actionDespesas_Avulsas = QAction(MainWindow)
        self.actionDespesas_Avulsas.setObjectName(u"actionDespesas_Avulsas")
        self.actionMovimenta_o = QAction(MainWindow)
        self.actionMovimenta_o.setObjectName(u"actionMovimenta_o")
        self.actionRelat_rios = QAction(MainWindow)
        self.actionRelat_rios.setObjectName(u"actionRelat_rios")
        self.actionDespesa_Fixas_2 = QAction(MainWindow)
        self.actionDespesa_Fixas_2.setObjectName(u"actionDespesa_Fixas_2")
        self.actionDespesa_Corrente = QAction(MainWindow)
        self.actionDespesa_Corrente.setObjectName(u"actionDespesa_Corrente")
        self.actionMovimenta_es = QAction(MainWindow)
        self.actionMovimenta_es.setObjectName(u"actionMovimenta_es")
        self.actionReceitas_Fixas = QAction(MainWindow)
        self.actionReceitas_Fixas.setObjectName(u"actionReceitas_Fixas")
        self.actionReceitas_Correntes = QAction(MainWindow)
        self.actionReceitas_Correntes.setObjectName(u"actionReceitas_Correntes")
        self.actionRelat_rios_2 = QAction(MainWindow)
        self.actionRelat_rios_2.setObjectName(u"actionRelat_rios_2")
        self.actionLan_amento_2 = QAction(MainWindow)
        self.actionLan_amento_2.setObjectName(u"actionLan_amento_2")
        self.actionMovimenta_es_2 = QAction(MainWindow)
        self.actionMovimenta_es_2.setObjectName(u"actionMovimenta_es_2")
        self.actionRelat_rios_3 = QAction(MainWindow)
        self.actionRelat_rios_3.setObjectName(u"actionRelat_rios_3")
        self.actionMovimenta_es_3 = QAction(MainWindow)
        self.actionMovimenta_es_3.setObjectName(u"actionMovimenta_es_3")
        self.actionRelat_rios_4 = QAction(MainWindow)
        self.actionRelat_rios_4.setObjectName(u"actionRelat_rios_4")
        self.actionInvent_rio = QAction(MainWindow)
        self.actionInvent_rio.setObjectName(u"actionInvent_rio")
        self.actionAdd_item = QAction(MainWindow)
        self.actionAdd_item.setObjectName(u"actionAdd_item")
        self.actionBaixa_de_Estoque = QAction(MainWindow)
        self.actionBaixa_de_Estoque.setObjectName(u"actionBaixa_de_Estoque")
        self.actionOrigens = QAction(MainWindow)
        self.actionOrigens.setObjectName(u"actionOrigens")
        self.actionProdutos_itens = QAction(MainWindow)
        self.actionProdutos_itens.setObjectName(u"actionProdutos_itens")
        self.actionCategoria = QAction(MainWindow)
        self.actionCategoria.setObjectName(u"actionCategoria")
        self.actionCategoria_2 = QAction(MainWindow)
        self.actionCategoria_2.setObjectName(u"actionCategoria_2")
        self.actionClasse = QAction(MainWindow)
        self.actionClasse.setObjectName(u"actionClasse")
        self.actionEmpresa = QAction(MainWindow)
        self.actionEmpresa.setObjectName(u"actionEmpresa")
        self.actionInstitui_es = QAction(MainWindow)
        self.actionInstitui_es.setObjectName(u"actionInstitui_es")
        self.actionAg_ncia = QAction(MainWindow)
        self.actionAg_ncia.setObjectName(u"actionAg_ncia")
        self.actionAg_ncia_2 = QAction(MainWindow)
        self.actionAg_ncia_2.setObjectName(u"actionAg_ncia_2")
        self.actionConta = QAction(MainWindow)
        self.actionConta.setObjectName(u"actionConta")
        self.actionCadUser = QAction(MainWindow)
        self.actionCadUser.setObjectName(u"actionCadUser")
        icon = QIcon()
        icon.addFile(u":/icons/add_user_dark.png", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.actionCadUser.setIcon(icon)
        self.actionGrupo = QAction(MainWindow)
        self.actionGrupo.setObjectName(u"actionGrupo")
        self.actionFornecedor = QAction(MainWindow)
        self.actionFornecedor.setObjectName(u"actionFornecedor")
        self.actionOrigem = QAction(MainWindow)
        self.actionOrigem.setObjectName(u"actionOrigem")
        self.actionCategoria_3 = QAction(MainWindow)
        self.actionCategoria_3.setObjectName(u"actionCategoria_3")
        self.actionOrigem_2 = QAction(MainWindow)
        self.actionOrigem_2.setObjectName(u"actionOrigem_2")
        self.actionCategoria_4 = QAction(MainWindow)
        self.actionCategoria_4.setObjectName(u"actionCategoria_4")
        self.actionMovimenta_o_2 = QAction(MainWindow)
        self.actionMovimenta_o_2.setObjectName(u"actionMovimenta_o_2")
        self.actionRamo_Atividade = QAction(MainWindow)
        self.actionRamo_Atividade.setObjectName(u"actionRamo_Atividade")
        self.actionLancarDia = QAction(MainWindow)
        self.actionLancarDia.setObjectName(u"actionLancarDia")
        self.actionBloquear = QAction(MainWindow)
        self.actionBloquear.setObjectName(u"actionBloquear")
        self.actionSair = QAction(MainWindow)
        self.actionSair.setObjectName(u"actionSair")
        self.actionLan_amento = QAction(MainWindow)
        self.actionLan_amento.setObjectName(u"actionLan_amento")
        self.actionRelat_rios_5 = QAction(MainWindow)
        self.actionRelat_rios_5.setObjectName(u"actionRelat_rios_5")
        self.actionRelat_rios_6 = QAction(MainWindow)
        self.actionRelat_rios_6.setObjectName(u"actionRelat_rios_6")
        self.actionReceitas_Fixas_2 = QAction(MainWindow)
        self.actionReceitas_Fixas_2.setObjectName(u"actionReceitas_Fixas_2")
        self.actionLan_amento_4 = QAction(MainWindow)
        self.actionLan_amento_4.setObjectName(u"actionLan_amento_4")
        self.actionLan_amento_5 = QAction(MainWindow)
        self.actionLan_amento_5.setObjectName(u"actionLan_amento_5")
        self.actionMovimenta_o_3 = QAction(MainWindow)
        self.actionMovimenta_o_3.setObjectName(u"actionMovimenta_o_3")
        self.actionRelat_rios_7 = QAction(MainWindow)
        self.actionRelat_rios_7.setObjectName(u"actionRelat_rios_7")
        self.actionLan_amento_6 = QAction(MainWindow)
        self.actionLan_amento_6.setObjectName(u"actionLan_amento_6")
        self.centralwidget = QWidget(MainWindow)
        self.centralwidget.setObjectName(u"centralwidget")
        self.verticalLayout_3 = QVBoxLayout(self.centralwidget)
        self.verticalLayout_3.setSpacing(0)
        self.verticalLayout_3.setObjectName(u"verticalLayout_3")
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.frame_3 = QFrame(self.centralwidget)
        self.frame_3.setObjectName(u"frame_3")
        self.frame_3.setFrameShape(QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QFrame.Raised)
        self.horizontalLayout = QHBoxLayout(self.frame_3)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName(u"horizontalLayout")
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.frame = QFrame(self.frame_3)
        self.frame.setObjectName(u"frame")
        self.frame.setMinimumSize(QSize(181, 0))
        self.frame.setMaximumSize(QSize(155, 16777215))
        font = QFont()
        font.setFamilies([u"Segoe UI"])
        font.setPointSize(13)
        font.setBold(False)
        font.setItalic(False)
        self.frame.setFont(font)
        self.frame.setStyleSheet(u"font: 110 13pt \"Segoe UI\";\n"
" /*background-color: rgb(225, 225, 225);*/\n"
"text-align: left;\n"
"")
        self.frame.setFrameShape(QFrame.StyledPanel)
        self.frame.setFrameShadow(QFrame.Raised)
        self.verticalLayout = QVBoxLayout(self.frame)
        self.verticalLayout.setSpacing(6)
        self.verticalLayout.setObjectName(u"verticalLayout")
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.frame_2 = QFrame(self.frame)
        self.frame_2.setObjectName(u"frame_2")
        self.frame_2.setMinimumSize(QSize(0, 164))
        self.frame_2.setMaximumSize(QSize(16777215, 131))
        self.frame_2.setFrameShape(QFrame.NoFrame)
        self.frame_2.setFrameShadow(QFrame.Raised)
        self.verticalLayout_2 = QVBoxLayout(self.frame_2)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName(u"verticalLayout_2")
        self.verticalLayout_2.setContentsMargins(0, 0, 15, 0)
        self.label = QLabel(self.frame_2)
        self.label.setObjectName(u"label")
        self.label.setWordWrap(True)

        self.verticalLayout_2.addWidget(self.label)


        self.verticalLayout.addWidget(self.frame_2)

        self.bnt_left_dashboard = QPushButton(self.frame)
        self.bnt_left_dashboard.setObjectName(u"bnt_left_dashboard")
        self.bnt_left_dashboard.setMinimumSize(QSize(121, 41))
        self.bnt_left_dashboard.setMaximumSize(QSize(1000, 41))
        self.bnt_left_dashboard.setCursor(QCursor(Qt.CursorShape.PointingHandCursor))
        self.bnt_left_dashboard.setFocusPolicy(Qt.NoFocus)
        self.bnt_left_dashboard.setLayoutDirection(Qt.LeftToRight)
        self.bnt_left_dashboard.setAutoFillBackground(False)
        self.bnt_left_dashboard.setStyleSheet(u"padding-left: 10px;\n"
"padding-top: 10px;")
        icon1 = QIcon()
        icon1.addFile(u":/icons/dashboard_light.png", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.bnt_left_dashboard.setIcon(icon1)
        self.bnt_left_dashboard.setIconSize(QSize(30, 30))
        self.bnt_left_dashboard.setCheckable(False)
        self.bnt_left_dashboard.setFlat(True)

        self.verticalLayout.addWidget(self.bnt_left_dashboard)

        self.bnt_left_despesa = QPushButton(self.frame)
        self.bnt_left_despesa.setObjectName(u"bnt_left_despesa")
        self.bnt_left_despesa.setMinimumSize(QSize(121, 41))
        self.bnt_left_despesa.setMaximumSize(QSize(1000, 41))
        self.bnt_left_despesa.setCursor(QCursor(Qt.CursorShape.PointingHandCursor))
        self.bnt_left_despesa.setAcceptDrops(False)
#if QT_CONFIG(tooltip)
        self.bnt_left_despesa.setToolTip(u"<html><head/><body><p><span style=\" font-size:11pt; font-weight:600; font-style:italic;\">Despesa...</span></p></body></html>")
#endif // QT_CONFIG(tooltip)
        self.bnt_left_despesa.setAutoFillBackground(False)
        self.bnt_left_despesa.setStyleSheet(u"padding-left: 10px;")
        icon2 = QIcon()
        icon2.addFile(u":/icons/despesa_light.png", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.bnt_left_despesa.setIcon(icon2)
        self.bnt_left_despesa.setIconSize(QSize(35, 35))
        self.bnt_left_despesa.setCheckable(False)
        self.bnt_left_despesa.setAutoRepeat(False)
        self.bnt_left_despesa.setAutoExclusive(False)
        self.bnt_left_despesa.setFlat(True)

        self.verticalLayout.addWidget(self.bnt_left_despesa)

        self.bnt_left_receitas = QPushButton(self.frame)
        self.bnt_left_receitas.setObjectName(u"bnt_left_receitas")
        sizePolicy = QSizePolicy(QSizePolicy.Policy.Fixed, QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bnt_left_receitas.sizePolicy().hasHeightForWidth())
        self.bnt_left_receitas.setSizePolicy(sizePolicy)
        self.bnt_left_receitas.setMinimumSize(QSize(121, 41))
        self.bnt_left_receitas.setMaximumSize(QSize(1000, 41))
        self.bnt_left_receitas.setCursor(QCursor(Qt.CursorShape.PointingHandCursor))
        self.bnt_left_receitas.setMouseTracking(False)
        self.bnt_left_receitas.setContextMenuPolicy(Qt.DefaultContextMenu)
        self.bnt_left_receitas.setLayoutDirection(Qt.LeftToRight)
        self.bnt_left_receitas.setAutoFillBackground(False)
        self.bnt_left_receitas.setStyleSheet(u"padding-left: 10px;")
        icon3 = QIcon()
        icon3.addFile(u":/icons/receita_light.png", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.bnt_left_receitas.setIcon(icon3)
        self.bnt_left_receitas.setIconSize(QSize(35, 35))
        self.bnt_left_receitas.setCheckable(False)
        self.bnt_left_receitas.setFlat(True)

        self.verticalLayout.addWidget(self.bnt_left_receitas)

        self.bnt_left_investimento = QPushButton(self.frame)
        self.bnt_left_investimento.setObjectName(u"bnt_left_investimento")
        self.bnt_left_investimento.setMinimumSize(QSize(121, 41))
        self.bnt_left_investimento.setMaximumSize(QSize(1000, 41))
        self.bnt_left_investimento.setCursor(QCursor(Qt.CursorShape.PointingHandCursor))
        self.bnt_left_investimento.setAutoFillBackground(False)
        self.bnt_left_investimento.setStyleSheet(u"padding-left: 10px;")
        icon4 = QIcon()
        icon4.addFile(u":/icons/investimento_light.png", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.bnt_left_investimento.setIcon(icon4)
        self.bnt_left_investimento.setIconSize(QSize(35, 35))
        self.bnt_left_investimento.setCheckable(False)
        self.bnt_left_investimento.setFlat(True)

        self.verticalLayout.addWidget(self.bnt_left_investimento)

        self.bnt_left_carteira = QPushButton(self.frame)
        self.bnt_left_carteira.setObjectName(u"bnt_left_carteira")
        self.bnt_left_carteira.setMinimumSize(QSize(121, 41))
        self.bnt_left_carteira.setMaximumSize(QSize(1000, 41))
        self.bnt_left_carteira.setCursor(QCursor(Qt.CursorShape.PointingHandCursor))
        self.bnt_left_carteira.setAutoFillBackground(False)
        self.bnt_left_carteira.setStyleSheet(u"padding-left: 10px;")
        icon5 = QIcon()
        icon5.addFile(u":/icons/carteira_light.png", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.bnt_left_carteira.setIcon(icon5)
        self.bnt_left_carteira.setIconSize(QSize(35, 35))
        self.bnt_left_carteira.setCheckable(False)
        self.bnt_left_carteira.setFlat(True)

        self.verticalLayout.addWidget(self.bnt_left_carteira)

        self.bnt_left_inventario = QPushButton(self.frame)
        self.bnt_left_inventario.setObjectName(u"bnt_left_inventario")
        self.bnt_left_inventario.setMinimumSize(QSize(121, 41))
        self.bnt_left_inventario.setMaximumSize(QSize(1000, 41))
        self.bnt_left_inventario.setCursor(QCursor(Qt.CursorShape.PointingHandCursor))
        self.bnt_left_inventario.setAutoFillBackground(False)
        self.bnt_left_inventario.setStyleSheet(u"padding-left: 10px;")
        icon6 = QIcon()
        icon6.addFile(u":/icons/inventario_light.png", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.bnt_left_inventario.setIcon(icon6)
        self.bnt_left_inventario.setIconSize(QSize(35, 35))
        self.bnt_left_inventario.setCheckable(False)
        self.bnt_left_inventario.setFlat(True)

        self.verticalLayout.addWidget(self.bnt_left_inventario)

        self.verticalSpacer = QSpacerItem(20, 130, QSizePolicy.Policy.Minimum, QSizePolicy.Policy.Expanding)

        self.verticalLayout.addItem(self.verticalSpacer)

        self.line = QFrame(self.frame)
        self.line.setObjectName(u"line")
        self.line.setFrameShape(QFrame.Shape.HLine)
        self.line.setFrameShadow(QFrame.Shadow.Sunken)

        self.verticalLayout.addWidget(self.line)

        self.bnt_left_config = QPushButton(self.frame)
        self.bnt_left_config.setObjectName(u"bnt_left_config")
        self.bnt_left_config.setMinimumSize(QSize(121, 41))
        self.bnt_left_config.setMaximumSize(QSize(1000, 41))
        self.bnt_left_config.setCursor(QCursor(Qt.CursorShape.PointingHandCursor))
        self.bnt_left_config.setAutoFillBackground(False)
        self.bnt_left_config.setStyleSheet(u"padding-left: 10px;\n"
"border-top: 1px black ;")
        icon7 = QIcon()
        icon7.addFile(u":/icons/config_light.png", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.bnt_left_config.setIcon(icon7)
        self.bnt_left_config.setIconSize(QSize(30, 30))
        self.bnt_left_config.setCheckable(False)
        self.bnt_left_config.setFlat(True)

        self.verticalLayout.addWidget(self.bnt_left_config)


        self.horizontalLayout.addWidget(self.frame)

        self.mdi_center = QMdiArea(self.frame_3)
        self.mdi_center.setObjectName(u"mdi_center")
        self.mdi_center.setStyleSheet(u"")
        self.mdi_center.setFrameShape(QFrame.NoFrame)
        self.mdi_center.setFrameShadow(QFrame.Plain)
        self.mdi_center.setLineWidth(0)
        self.mdi_center.setVerticalScrollBarPolicy(Qt.ScrollBarAsNeeded)
        self.mdi_center.setHorizontalScrollBarPolicy(Qt.ScrollBarAsNeeded)
        self.mdi_center.setSizeAdjustPolicy(QAbstractScrollArea.AdjustToContentsOnFirstShow)
        brush = QBrush(QColor(0, 0, 0, 0))
        brush.setStyle(Qt.NoBrush)
        self.mdi_center.setBackground(brush)
        self.mdi_center.setActivationOrder(QMdiArea.ActivationHistoryOrder)
        self.mdi_center.setViewMode(QMdiArea.SubWindowView)
        self.mdi_center.setDocumentMode(False)
        self.mdi_center.setTabsClosable(False)
        self.mdi_center.setTabsMovable(False)
        self.mdi_center.setTabPosition(QTabWidget.South)

        self.horizontalLayout.addWidget(self.mdi_center)


        self.verticalLayout_3.addWidget(self.frame_3)

        self.frame_5 = QFrame(self.centralwidget)
        self.frame_5.setObjectName(u"frame_5")
        self.frame_5.setMinimumSize(QSize(0, 20))
        self.frame_5.setMaximumSize(QSize(16777215, 41))
        self.frame_5.setFrameShape(QFrame.Panel)
        self.frame_5.setFrameShadow(QFrame.Raised)
        self.horizontalLayout_4 = QHBoxLayout(self.frame_5)
        self.horizontalLayout_4.setObjectName(u"horizontalLayout_4")
        self.horizontalLayout_4.setContentsMargins(10, 0, 0, 0)
        self.horizontalLayout_2 = QHBoxLayout()
        self.horizontalLayout_2.setObjectName(u"horizontalLayout_2")
        self.label_2 = QLabel(self.frame_5)
        self.label_2.setObjectName(u"label_2")

        self.horizontalLayout_2.addWidget(self.label_2)

        self.lbl_user_conect = QLabel(self.frame_5)
        self.lbl_user_conect.setObjectName(u"lbl_user_conect")
        sizePolicy1 = QSizePolicy(QSizePolicy.Policy.MinimumExpanding, QSizePolicy.Policy.Preferred)
        sizePolicy1.setHorizontalStretch(0)
        sizePolicy1.setVerticalStretch(0)
        sizePolicy1.setHeightForWidth(self.lbl_user_conect.sizePolicy().hasHeightForWidth())
        self.lbl_user_conect.setSizePolicy(sizePolicy1)

        self.horizontalLayout_2.addWidget(self.lbl_user_conect)


        self.horizontalLayout_4.addLayout(self.horizontalLayout_2)

        self.horizontalLayout_3 = QHBoxLayout()
        self.horizontalLayout_3.setObjectName(u"horizontalLayout_3")
        self.label_3 = QLabel(self.frame_5)
        self.label_3.setObjectName(u"label_3")

        self.horizontalLayout_3.addWidget(self.label_3)

        self.lbl_empresa_conect = QLabel(self.frame_5)
        self.lbl_empresa_conect.setObjectName(u"lbl_empresa_conect")
        sizePolicy1.setHeightForWidth(self.lbl_empresa_conect.sizePolicy().hasHeightForWidth())
        self.lbl_empresa_conect.setSizePolicy(sizePolicy1)

        self.horizontalLayout_3.addWidget(self.lbl_empresa_conect)


        self.horizontalLayout_4.addLayout(self.horizontalLayout_3)

        self.horizontalSpacer = QSpacerItem(838, 15, QSizePolicy.Policy.Expanding, QSizePolicy.Policy.Minimum)

        self.horizontalLayout_4.addItem(self.horizontalSpacer)


        self.verticalLayout_3.addWidget(self.frame_5)

        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QMenuBar(MainWindow)
        self.menubar.setObjectName(u"menubar")
        self.menubar.setGeometry(QRect(0, 0, 1232, 21))
        self.menuSistema = QMenu(self.menubar)
        self.menuSistema.setObjectName(u"menuSistema")
        self.menuCadastro = QMenu(self.menubar)
        self.menuCadastro.setObjectName(u"menuCadastro")
        self.menuProdutos_Itens = QMenu(self.menuCadastro)
        self.menuProdutos_Itens.setObjectName(u"menuProdutos_Itens")
        self.menuAuxiliares = QMenu(self.menuCadastro)
        self.menuAuxiliares.setObjectName(u"menuAuxiliares")
        self.menuBancos = QMenu(self.menuAuxiliares)
        self.menuBancos.setObjectName(u"menuBancos")
        self.menuDespesa_2 = QMenu(self.menuAuxiliares)
        self.menuDespesa_2.setObjectName(u"menuDespesa_2")
        self.menuReceita = QMenu(self.menuAuxiliares)
        self.menuReceita.setObjectName(u"menuReceita")
        self.menuConta_Corrente = QMenu(self.menuCadastro)
        self.menuConta_Corrente.setObjectName(u"menuConta_Corrente")
        self.menuUsu_rios = QMenu(self.menuCadastro)
        self.menuUsu_rios.setObjectName(u"menuUsu_rios")
        self.menuConfiguracoes = QMenu(self.menubar)
        self.menuConfiguracoes.setObjectName(u"menuConfiguracoes")
        self.menuRelatorios = QMenu(self.menubar)
        self.menuRelatorios.setObjectName(u"menuRelatorios")
        self.menuEstoque = QMenu(self.menubar)
        self.menuEstoque.setObjectName(u"menuEstoque")
        self.menuLan_amento_2 = QMenu(self.menuEstoque)
        self.menuLan_amento_2.setObjectName(u"menuLan_amento_2")
        self.menuFinanceiro = QMenu(self.menubar)
        self.menuFinanceiro.setObjectName(u"menuFinanceiro")
        self.menuDespesas = QMenu(self.menuFinanceiro)
        self.menuDespesas.setObjectName(u"menuDespesas")
        self.menuReceitas_2 = QMenu(self.menuFinanceiro)
        self.menuReceitas_2.setObjectName(u"menuReceitas_2")
        self.menuInvestimento_2 = QMenu(self.menuFinanceiro)
        self.menuInvestimento_2.setObjectName(u"menuInvestimento_2")
        self.menuOutros = QMenu(self.menubar)
        self.menuOutros.setObjectName(u"menuOutros")
        self.menuEntregas = QMenu(self.menuOutros)
        self.menuEntregas.setObjectName(u"menuEntregas")
        self.menuCompras = QMenu(self.menubar)
        self.menuCompras.setObjectName(u"menuCompras")
        self.menuRequisi_o = QMenu(self.menuCompras)
        self.menuRequisi_o.setObjectName(u"menuRequisi_o")
        MainWindow.setMenuBar(self.menubar)

        self.menubar.addAction(self.menuSistema.menuAction())
        self.menubar.addAction(self.menuCadastro.menuAction())
        self.menubar.addAction(self.menuCompras.menuAction())
        self.menubar.addAction(self.menuFinanceiro.menuAction())
        self.menubar.addAction(self.menuEstoque.menuAction())
        self.menubar.addAction(self.menuRelatorios.menuAction())
        self.menubar.addAction(self.menuOutros.menuAction())
        self.menubar.addAction(self.menuConfiguracoes.menuAction())
        self.menuSistema.addAction(self.actionEmpresa)
        self.menuSistema.addSeparator()
        self.menuSistema.addAction(self.actionBloquear)
        self.menuSistema.addAction(self.actionSair)
        self.menuCadastro.addAction(self.menuProdutos_Itens.menuAction())
        self.menuCadastro.addAction(self.actionFornecedor)
        self.menuCadastro.addAction(self.menuUsu_rios.menuAction())
        self.menuCadastro.addAction(self.menuConta_Corrente.menuAction())
        self.menuCadastro.addSeparator()
        self.menuCadastro.addAction(self.menuAuxiliares.menuAction())
        self.menuProdutos_Itens.addAction(self.actionProdutos_itens)
        self.menuProdutos_Itens.addAction(self.actionCategoria_2)
        self.menuProdutos_Itens.addAction(self.actionClasse)
        self.menuAuxiliares.addAction(self.menuBancos.menuAction())
        self.menuAuxiliares.addAction(self.menuDespesa_2.menuAction())
        self.menuAuxiliares.addAction(self.menuReceita.menuAction())
        self.menuAuxiliares.addAction(self.actionRamo_Atividade)
        self.menuBancos.addAction(self.actionInstitui_es)
        self.menuBancos.addAction(self.actionAg_ncia)
        self.menuDespesa_2.addAction(self.actionOrigem)
        self.menuDespesa_2.addAction(self.actionCategoria_3)
        self.menuReceita.addAction(self.actionOrigem_2)
        self.menuReceita.addAction(self.actionCategoria_4)
        self.menuConta_Corrente.addAction(self.actionAg_ncia_2)
        self.menuConta_Corrente.addAction(self.actionConta)
        self.menuUsu_rios.addAction(self.actionCadUser)
        self.menuUsu_rios.addAction(self.actionGrupo)
        self.menuEstoque.addAction(self.menuLan_amento_2.menuAction())
        self.menuEstoque.addAction(self.actionMovimenta_es_3)
        self.menuEstoque.addAction(self.actionInvent_rio)
        self.menuEstoque.addSeparator()
        self.menuEstoque.addAction(self.actionRelat_rios_4)
        self.menuLan_amento_2.addAction(self.actionAdd_item)
        self.menuLan_amento_2.addAction(self.actionBaixa_de_Estoque)
        self.menuFinanceiro.addAction(self.actionMovimenta_o_2)
        self.menuFinanceiro.addAction(self.menuDespesas.menuAction())
        self.menuFinanceiro.addAction(self.menuReceitas_2.menuAction())
        self.menuFinanceiro.addAction(self.menuInvestimento_2.menuAction())
        self.menuDespesas.addAction(self.actionLan_amento)
        self.menuDespesas.addSeparator()
        self.menuDespesas.addAction(self.actionRelat_rios_5)
        self.menuReceitas_2.addAction(self.actionLan_amento_4)
        self.menuReceitas_2.addSeparator()
        self.menuReceitas_2.addAction(self.actionRelat_rios_6)
        self.menuInvestimento_2.addAction(self.actionLan_amento_5)
        self.menuInvestimento_2.addAction(self.actionMovimenta_o_3)
        self.menuInvestimento_2.addSeparator()
        self.menuInvestimento_2.addAction(self.actionRelat_rios_7)
        self.menuOutros.addAction(self.menuEntregas.menuAction())
        self.menuEntregas.addAction(self.actionLancarDia)
        self.menuCompras.addAction(self.menuRequisi_o.menuAction())
        self.menuRequisi_o.addAction(self.actionLan_amento_6)

        self.retranslateUi(MainWindow)

        self.bnt_left_dashboard.setDefault(False)
        self.bnt_left_despesa.setDefault(False)
        self.bnt_left_receitas.setDefault(False)
        self.bnt_left_investimento.setDefault(False)
        self.bnt_left_carteira.setDefault(False)
        self.bnt_left_inventario.setDefault(False)
        self.bnt_left_config.setDefault(False)


        QMetaObject.connectSlotsByName(MainWindow)
    # setupUi

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QCoreApplication.translate("MainWindow", u"MainWindow", None))
#if QT_CONFIG(whatsthis)
        MainWindow.setWhatsThis(QCoreApplication.translate("MainWindow", u"teste", None))
#endif // QT_CONFIG(whatsthis)
        self.actionReceitas.setText(QCoreApplication.translate("MainWindow", u"Receitas", None))
        self.actionInvestimentos.setText(QCoreApplication.translate("MainWindow", u"Investimentos", None))
        self.actionDespesa_Fixas.setText(QCoreApplication.translate("MainWindow", u"Despesa Fixas", None))
        self.actionDespesa_Correntes.setText(QCoreApplication.translate("MainWindow", u"Despesa Correntes", None))
        self.actionDespesas_Avulsas.setText(QCoreApplication.translate("MainWindow", u"Despesas Avulsas", None))
        self.actionMovimenta_o.setText(QCoreApplication.translate("MainWindow", u"Movimenta\u00e7\u00e3o", None))
        self.actionRelat_rios.setText(QCoreApplication.translate("MainWindow", u"Relat\u00f3rios", None))
        self.actionDespesa_Fixas_2.setText(QCoreApplication.translate("MainWindow", u"Despesa Fixa", None))
        self.actionDespesa_Corrente.setText(QCoreApplication.translate("MainWindow", u"Despesa Corrente", None))
        self.actionMovimenta_es.setText(QCoreApplication.translate("MainWindow", u"Movimenta\u00e7\u00f5es", None))
        self.actionReceitas_Fixas.setText(QCoreApplication.translate("MainWindow", u"Receitas Fixas", None))
        self.actionReceitas_Correntes.setText(QCoreApplication.translate("MainWindow", u"Receitas Correntes", None))
        self.actionRelat_rios_2.setText(QCoreApplication.translate("MainWindow", u"Relat\u00f3rios", None))
        self.actionLan_amento_2.setText(QCoreApplication.translate("MainWindow", u"Lan\u00e7amento", None))
        self.actionMovimenta_es_2.setText(QCoreApplication.translate("MainWindow", u"Movimenta\u00e7\u00f5es", None))
        self.actionRelat_rios_3.setText(QCoreApplication.translate("MainWindow", u"Relat\u00f3rios", None))
        self.actionMovimenta_es_3.setText(QCoreApplication.translate("MainWindow", u"Movimenta\u00e7\u00f5es", None))
        self.actionRelat_rios_4.setText(QCoreApplication.translate("MainWindow", u"Relat\u00f3rios", None))
        self.actionInvent_rio.setText(QCoreApplication.translate("MainWindow", u"Invent\u00e1rio", None))
        self.actionAdd_item.setText(QCoreApplication.translate("MainWindow", u"Add item ", None))
        self.actionBaixa_de_Estoque.setText(QCoreApplication.translate("MainWindow", u"Baixa de Estoque", None))
        self.actionOrigens.setText(QCoreApplication.translate("MainWindow", u"Origens", None))
        self.actionProdutos_itens.setText(QCoreApplication.translate("MainWindow", u"Produtos/itens", None))
        self.actionCategoria.setText(QCoreApplication.translate("MainWindow", u"Categoria", None))
        self.actionCategoria_2.setText(QCoreApplication.translate("MainWindow", u"Categoria", None))
        self.actionClasse.setText(QCoreApplication.translate("MainWindow", u"Classe ", None))
        self.actionEmpresa.setText(QCoreApplication.translate("MainWindow", u"Empresa", None))
        self.actionInstitui_es.setText(QCoreApplication.translate("MainWindow", u"Institui\u00e7\u00f5es", None))
        self.actionAg_ncia.setText(QCoreApplication.translate("MainWindow", u"Ag\u00eancia", None))
        self.actionAg_ncia_2.setText(QCoreApplication.translate("MainWindow", u"Ag\u00eancia", None))
        self.actionConta.setText(QCoreApplication.translate("MainWindow", u"Conta ", None))
        self.actionCadUser.setText(QCoreApplication.translate("MainWindow", u"Usu\u00e1rio", None))
        self.actionGrupo.setText(QCoreApplication.translate("MainWindow", u"Grupo de usu\u00e1rios", None))
        self.actionFornecedor.setText(QCoreApplication.translate("MainWindow", u"Fornecedor", None))
        self.actionOrigem.setText(QCoreApplication.translate("MainWindow", u"Origem ", None))
        self.actionCategoria_3.setText(QCoreApplication.translate("MainWindow", u"Categoria ", None))
        self.actionOrigem_2.setText(QCoreApplication.translate("MainWindow", u"Origem", None))
        self.actionCategoria_4.setText(QCoreApplication.translate("MainWindow", u"Categoria", None))
        self.actionMovimenta_o_2.setText(QCoreApplication.translate("MainWindow", u"Movimenta\u00e7\u00e3o", None))
        self.actionRamo_Atividade.setText(QCoreApplication.translate("MainWindow", u"Ramo Atividade", None))
        self.actionLancarDia.setText(QCoreApplication.translate("MainWindow", u"Lan\u00e7ar Dia ", None))
        self.actionBloquear.setText(QCoreApplication.translate("MainWindow", u"Bloquear", None))
        self.actionSair.setText(QCoreApplication.translate("MainWindow", u"Sair", None))
        self.actionLan_amento.setText(QCoreApplication.translate("MainWindow", u"Lan\u00e7amento", None))
        self.actionRelat_rios_5.setText(QCoreApplication.translate("MainWindow", u"Relat\u00f3rios", None))
        self.actionRelat_rios_6.setText(QCoreApplication.translate("MainWindow", u"Relat\u00f3rios", None))
        self.actionReceitas_Fixas_2.setText(QCoreApplication.translate("MainWindow", u"Receitas Fixas", None))
        self.actionLan_amento_4.setText(QCoreApplication.translate("MainWindow", u"Lan\u00e7amento", None))
        self.actionLan_amento_5.setText(QCoreApplication.translate("MainWindow", u"Lan\u00e7amento", None))
        self.actionMovimenta_o_3.setText(QCoreApplication.translate("MainWindow", u"Movimenta\u00e7\u00e3o", None))
        self.actionRelat_rios_7.setText(QCoreApplication.translate("MainWindow", u"Relat\u00f3rios", None))
        self.actionLan_amento_6.setText(QCoreApplication.translate("MainWindow", u"Lan\u00e7amento", None))
        self.label.setText(QCoreApplication.translate("MainWindow", u"<html><head/><body><p><img src=\":/icons/image_prin.png\"width=\"200\" height=\"200\"/></p></body></html>", None))
#if QT_CONFIG(tooltip)
        self.bnt_left_dashboard.setToolTip(QCoreApplication.translate("MainWindow", u"<html><head/><body><p><span style=\" font-weight:600; font-style:italic;\">DashBoard...</span></p></body></html>", None))
#endif // QT_CONFIG(tooltip)
        self.bnt_left_dashboard.setText(QCoreApplication.translate("MainWindow", u"DashBoard", None))
        self.bnt_left_despesa.setText(QCoreApplication.translate("MainWindow", u"Despesa", None))
#if QT_CONFIG(tooltip)
        self.bnt_left_receitas.setToolTip(QCoreApplication.translate("MainWindow", u"<html><head/><body><p><span style=\" font-size:11pt; font-weight:600; font-style:italic;\">Receita...</span></p></body></html>", None))
#endif // QT_CONFIG(tooltip)
        self.bnt_left_receitas.setText(QCoreApplication.translate("MainWindow", u"Receitas", None))
#if QT_CONFIG(tooltip)
        self.bnt_left_investimento.setToolTip(QCoreApplication.translate("MainWindow", u"<html><head/><body><p><span style=\" font-size:11pt; font-weight:600; font-style:italic;\">Investimento...</span></p></body></html>", None))
#endif // QT_CONFIG(tooltip)
        self.bnt_left_investimento.setText(QCoreApplication.translate("MainWindow", u"Investimento", None))
#if QT_CONFIG(tooltip)
        self.bnt_left_carteira.setToolTip(QCoreApplication.translate("MainWindow", u"<html><head/><body><p><span style=\" font-size:11pt; font-weight:600; font-style:italic;\">Carteira...</span></p></body></html>", None))
#endif // QT_CONFIG(tooltip)
        self.bnt_left_carteira.setText(QCoreApplication.translate("MainWindow", u"Carteira", None))
#if QT_CONFIG(tooltip)
        self.bnt_left_inventario.setToolTip(QCoreApplication.translate("MainWindow", u"<html><head/><body><p><span style=\" font-size:11pt; font-weight:600; font-style:italic;\">Invent\u00e1rio...</span></p></body></html>", None))
#endif // QT_CONFIG(tooltip)
        self.bnt_left_inventario.setText(QCoreApplication.translate("MainWindow", u"Invent\u00e1rio", None))
#if QT_CONFIG(tooltip)
        self.bnt_left_config.setToolTip(QCoreApplication.translate("MainWindow", u"<html><head/><body><p><span style=\" font-size:11pt; font-weight:600; font-style:italic;\">Configura\u00e7\u00f5es...</span></p></body></html>", None))
#endif // QT_CONFIG(tooltip)
        self.bnt_left_config.setText(QCoreApplication.translate("MainWindow", u"Configura\u00e7\u00f5es", None))
        self.label_2.setText(QCoreApplication.translate("MainWindow", u"Usu\u00e1rio :", None))
        self.lbl_user_conect.setText(QCoreApplication.translate("MainWindow", u"....", None))
        self.label_3.setText(QCoreApplication.translate("MainWindow", u"Empresa :", None))
        self.lbl_empresa_conect.setText(QCoreApplication.translate("MainWindow", u"....", None))
        self.menuSistema.setTitle(QCoreApplication.translate("MainWindow", u"Sistema", None))
        self.menuCadastro.setTitle(QCoreApplication.translate("MainWindow", u"Cadastro", None))
        self.menuProdutos_Itens.setTitle(QCoreApplication.translate("MainWindow", u"Produtos/Itens", None))
        self.menuAuxiliares.setTitle(QCoreApplication.translate("MainWindow", u"Auxiliares", None))
        self.menuBancos.setTitle(QCoreApplication.translate("MainWindow", u"Bancos", None))
        self.menuDespesa_2.setTitle(QCoreApplication.translate("MainWindow", u"Despesa", None))
        self.menuReceita.setTitle(QCoreApplication.translate("MainWindow", u"Receita", None))
        self.menuConta_Corrente.setTitle(QCoreApplication.translate("MainWindow", u"Conta Corrente", None))
        self.menuUsu_rios.setTitle(QCoreApplication.translate("MainWindow", u"Usu\u00e1rios", None))
        self.menuConfiguracoes.setTitle(QCoreApplication.translate("MainWindow", u"Configura\u00e7\u00f5es", None))
        self.menuRelatorios.setTitle(QCoreApplication.translate("MainWindow", u"Relat\u00f3rios", None))
        self.menuEstoque.setTitle(QCoreApplication.translate("MainWindow", u"Estoque", None))
        self.menuLan_amento_2.setTitle(QCoreApplication.translate("MainWindow", u"Lan\u00e7amento", None))
        self.menuFinanceiro.setTitle(QCoreApplication.translate("MainWindow", u"Financeiro", None))
        self.menuDespesas.setTitle(QCoreApplication.translate("MainWindow", u"Despesas", None))
        self.menuReceitas_2.setTitle(QCoreApplication.translate("MainWindow", u"Receitas", None))
        self.menuInvestimento_2.setTitle(QCoreApplication.translate("MainWindow", u"Investimento", None))
        self.menuOutros.setTitle(QCoreApplication.translate("MainWindow", u"Outros", None))
        self.menuEntregas.setTitle(QCoreApplication.translate("MainWindow", u"Entregas", None))
        self.menuCompras.setTitle(QCoreApplication.translate("MainWindow", u"Compras", None))
        self.menuRequisi_o.setTitle(QCoreApplication.translate("MainWindow", u"Requisi\u00e7\u00e3o", None))
    # retranslateUi

