# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'CadFornecedor.ui'
##
## Created by: Qt User Interface Compiler version 6.7.2
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QBrush, QColor, QConicalGradient, QCursor,
    QFont, QFontDatabase, QGradient, QIcon,
    QImage, QKeySequence, QLinearGradient, QPainter,
    QPalette, QPixmap, QRadialGradient, QTransform)
from PySide6.QtWidgets import (QApplication, QCheckBox, QDateEdit, QDialog,
    QGroupBox, QLCDNumber, QLabel, QLineEdit,
    QPlainTextEdit, QPushButton, QRadioButton, QSizePolicy,
    QTabWidget, QWidget)

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        if not Dialog.objectName():
            Dialog.setObjectName(u"Dialog")
        Dialog.resize(720, 545)
        self.tabWidget = QTabWidget(Dialog)
        self.tabWidget.setObjectName(u"tabWidget")
        self.tabWidget.setGeometry(QRect(0, 0, 721, 491))
        font = QFont()
        font.setFamilies([u"Segoe UI"])
        font.setPointSize(12)
        self.tabWidget.setFont(font)
        self.tabWidget.setCursor(QCursor(Qt.CursorShape.PointingHandCursor))
        self.tabWidget.setContextMenuPolicy(Qt.DefaultContextMenu)
        self.tabWidget.setAcceptDrops(False)
        self.tabWidget.setStyleSheet(u"font: 12pt \"Segoe UI\";")
        self.DdPrincipais = QWidget()
        self.DdPrincipais.setObjectName(u"DdPrincipais")
        self.lcdNumber = QLCDNumber(self.DdPrincipais)
        self.lcdNumber.setObjectName(u"lcdNumber")
        self.lcdNumber.setGeometry(QRect(20, 10, 91, 23))
        self.label_10 = QLabel(self.DdPrincipais)
        self.label_10.setObjectName(u"label_10")
        self.label_10.setGeometry(QRect(20, 140, 121, 16))
        self.label_10.setFont(font)
        self.lineEdit_8 = QLineEdit(self.DdPrincipais)
        self.lineEdit_8.setObjectName(u"lineEdit_8")
        self.lineEdit_8.setGeometry(QRect(20, 160, 591, 21))
        self.lineEdit_8.setFont(font)
        self.lineEdit = QLineEdit(self.DdPrincipais)
        self.lineEdit.setObjectName(u"lineEdit")
        self.lineEdit.setGeometry(QRect(20, 110, 591, 21))
        font1 = QFont()
        font1.setFamilies([u"Segoe UI"])
        font1.setPointSize(12)
        font1.setStyleStrategy(QFont.NoAntialias)
        self.lineEdit.setFont(font1)
        self.label = QLabel(self.DdPrincipais)
        self.label.setObjectName(u"label")
        self.label.setGeometry(QRect(20, 90, 91, 16))
        self.label.setFont(font)
        self.dateEdit_3 = QDateEdit(self.DdPrincipais)
        self.dateEdit_3.setObjectName(u"dateEdit_3")
        self.dateEdit_3.setGeometry(QRect(290, 60, 131, 22))
        self.dateEdit_3.setCalendarPopup(True)
        self.label_15 = QLabel(self.DdPrincipais)
        self.label_15.setObjectName(u"label_15")
        self.label_15.setGeometry(QRect(290, 40, 121, 16))
        self.label_15.setFont(font)
        self.label_13 = QLabel(self.DdPrincipais)
        self.label_13.setObjectName(u"label_13")
        self.label_13.setGeometry(QRect(20, 40, 141, 21))
        self.lineEdit_11 = QLineEdit(self.DdPrincipais)
        self.lineEdit_11.setObjectName(u"lineEdit_11")
        self.lineEdit_11.setGeometry(QRect(20, 60, 241, 21))
        self.lineEdit_11.setCursorPosition(0)
        self.radioButton = QRadioButton(self.DdPrincipais)
        self.radioButton.setObjectName(u"radioButton")
        self.radioButton.setGeometry(QRect(390, 10, 131, 17))
        self.radioButton_2 = QRadioButton(self.DdPrincipais)
        self.radioButton_2.setObjectName(u"radioButton_2")
        self.radioButton_2.setGeometry(QRect(510, 10, 131, 17))
        self.groupBox = QGroupBox(self.DdPrincipais)
        self.groupBox.setObjectName(u"groupBox")
        self.groupBox.setGeometry(QRect(20, 270, 591, 171))
        self.checkBox_6 = QCheckBox(self.groupBox)
        self.checkBox_6.setObjectName(u"checkBox_6")
        self.checkBox_6.setGeometry(QRect(10, 40, 221, 17))
        self.checkBox_6.setChecked(False)
        self.checkBox_7 = QCheckBox(self.groupBox)
        self.checkBox_7.setObjectName(u"checkBox_7")
        self.checkBox_7.setGeometry(QRect(10, 70, 281, 17))
        self.checkBox_7.setChecked(False)
        self.lineEdit_14 = QLineEdit(self.groupBox)
        self.lineEdit_14.setObjectName(u"lineEdit_14")
        self.lineEdit_14.setGeometry(QRect(10, 120, 241, 21))
        self.lineEdit_14.setCursorPosition(0)
        self.label_17 = QLabel(self.groupBox)
        self.label_17.setObjectName(u"label_17")
        self.label_17.setGeometry(QRect(10, 100, 141, 21))
        self.lineEdit_12 = QLineEdit(self.DdPrincipais)
        self.lineEdit_12.setObjectName(u"lineEdit_12")
        self.lineEdit_12.setGeometry(QRect(20, 210, 241, 21))
        self.lineEdit_12.setCursorPosition(0)
        self.label_14 = QLabel(self.DdPrincipais)
        self.label_14.setObjectName(u"label_14")
        self.label_14.setGeometry(QRect(20, 190, 141, 21))
        self.lineEdit_13 = QLineEdit(self.DdPrincipais)
        self.lineEdit_13.setObjectName(u"lineEdit_13")
        self.lineEdit_13.setGeometry(QRect(270, 210, 241, 21))
        self.lineEdit_13.setCursorPosition(0)
        self.label_16 = QLabel(self.DdPrincipais)
        self.label_16.setObjectName(u"label_16")
        self.label_16.setGeometry(QRect(270, 190, 141, 21))
        self.tabWidget.addTab(self.DdPrincipais, "")
        self.DdAdicionais = QWidget()
        self.DdAdicionais.setObjectName(u"DdAdicionais")
        self.lineEdit_24 = QLineEdit(self.DdAdicionais)
        self.lineEdit_24.setObjectName(u"lineEdit_24")
        self.lineEdit_24.setGeometry(QRect(320, 70, 321, 21))
        self.lineEdit_25 = QLineEdit(self.DdAdicionais)
        self.lineEdit_25.setObjectName(u"lineEdit_25")
        self.lineEdit_25.setGeometry(QRect(520, 30, 121, 21))
        self.lineEdit_10 = QLineEdit(self.DdAdicionais)
        self.lineEdit_10.setObjectName(u"lineEdit_10")
        self.lineEdit_10.setGeometry(QRect(10, 30, 501, 21))
        self.label_28 = QLabel(self.DdAdicionais)
        self.label_28.setObjectName(u"label_28")
        self.label_28.setGeometry(QRect(320, 50, 211, 21))
        self.lineEdit_26 = QLineEdit(self.DdAdicionais)
        self.lineEdit_26.setObjectName(u"lineEdit_26")
        self.lineEdit_26.setGeometry(QRect(10, 120, 161, 21))
        self.lineEdit_27 = QLineEdit(self.DdAdicionais)
        self.lineEdit_27.setObjectName(u"lineEdit_27")
        self.lineEdit_27.setGeometry(QRect(10, 70, 291, 21))
        self.lineEdit_28 = QLineEdit(self.DdAdicionais)
        self.lineEdit_28.setObjectName(u"lineEdit_28")
        self.lineEdit_28.setGeometry(QRect(460, 180, 181, 21))
        self.lineEdit_28.setMaxLength(14)
        self.lineEdit_28.setCursorMoveStyle(Qt.VisualMoveStyle)
        self.plainTextEdit_2 = QPlainTextEdit(self.DdAdicionais)
        self.plainTextEdit_2.setObjectName(u"plainTextEdit_2")
        self.plainTextEdit_2.setGeometry(QRect(390, 230, 321, 131))
        self.checkBox_5 = QCheckBox(self.DdAdicionais)
        self.checkBox_5.setObjectName(u"checkBox_5")
        self.checkBox_5.setGeometry(QRect(210, 180, 151, 17))
        self.checkBox_5.setChecked(False)
        self.label_29 = QLabel(self.DdAdicionais)
        self.label_29.setObjectName(u"label_29")
        self.label_29.setGeometry(QRect(520, 10, 141, 21))
        self.lineEdit_29 = QLineEdit(self.DdAdicionais)
        self.lineEdit_29.setObjectName(u"lineEdit_29")
        self.lineEdit_29.setGeometry(QRect(10, 230, 351, 21))
        self.label_30 = QLabel(self.DdAdicionais)
        self.label_30.setObjectName(u"label_30")
        self.label_30.setGeometry(QRect(490, 100, 141, 21))
        self.label_31 = QLabel(self.DdAdicionais)
        self.label_31.setObjectName(u"label_31")
        self.label_31.setGeometry(QRect(10, 160, 131, 16))
        self.label_12 = QLabel(self.DdAdicionais)
        self.label_12.setObjectName(u"label_12")
        self.label_12.setGeometry(QRect(10, 10, 141, 21))
        self.label_32 = QLabel(self.DdAdicionais)
        self.label_32.setObjectName(u"label_32")
        self.label_32.setGeometry(QRect(390, 210, 131, 16))
        self.lineEdit_30 = QLineEdit(self.DdAdicionais)
        self.lineEdit_30.setObjectName(u"lineEdit_30")
        self.lineEdit_30.setGeometry(QRect(490, 120, 151, 21))
        self.lineEdit_30.setInputMethodHints(Qt.ImhNoAutoUppercase)
        self.lineEdit_30.setMaxLength(2)
        self.lineEdit_31 = QLineEdit(self.DdAdicionais)
        self.lineEdit_31.setObjectName(u"lineEdit_31")
        self.lineEdit_31.setGeometry(QRect(190, 120, 291, 21))
        self.lineEdit_32 = QLineEdit(self.DdAdicionais)
        self.lineEdit_32.setObjectName(u"lineEdit_32")
        self.lineEdit_32.setGeometry(QRect(10, 180, 181, 21))
        self.lineEdit_32.setMaxLength(15)
        self.lineEdit_32.setCursorMoveStyle(Qt.VisualMoveStyle)
        self.label_33 = QLabel(self.DdAdicionais)
        self.label_33.setObjectName(u"label_33")
        self.label_33.setGeometry(QRect(10, 50, 141, 21))
        self.label_34 = QLabel(self.DdAdicionais)
        self.label_34.setObjectName(u"label_34")
        self.label_34.setGeometry(QRect(10, 100, 141, 21))
        self.label_35 = QLabel(self.DdAdicionais)
        self.label_35.setObjectName(u"label_35")
        self.label_35.setGeometry(QRect(10, 210, 131, 16))
        self.label_36 = QLabel(self.DdAdicionais)
        self.label_36.setObjectName(u"label_36")
        self.label_36.setGeometry(QRect(460, 160, 131, 16))
        self.label_37 = QLabel(self.DdAdicionais)
        self.label_37.setObjectName(u"label_37")
        self.label_37.setGeometry(QRect(190, 100, 141, 21))
        self.tabWidget.addTab(self.DdAdicionais, "")
        self.pushButton_2 = QPushButton(Dialog)
        self.pushButton_2.setObjectName(u"pushButton_2")
        self.pushButton_2.setEnabled(True)
        self.pushButton_2.setGeometry(QRect(450, 500, 131, 41))
        self.pushButton_3 = QPushButton(Dialog)
        self.pushButton_3.setObjectName(u"pushButton_3")
        self.pushButton_3.setGeometry(QRect(10, 500, 131, 41))
        self.pushButton_4 = QPushButton(Dialog)
        self.pushButton_4.setObjectName(u"pushButton_4")
        self.pushButton_4.setGeometry(QRect(590, 500, 131, 41))
        self.pushButton_4.setCheckable(False)
        self.pushButton_4.setChecked(False)
        self.pushButton_4.setAutoRepeat(False)
        self.pushButton_5 = QPushButton(Dialog)
        self.pushButton_5.setObjectName(u"pushButton_5")
        self.pushButton_5.setEnabled(False)
        self.pushButton_5.setGeometry(QRect(310, 500, 131, 41))

        self.retranslateUi(Dialog)

        self.tabWidget.setCurrentIndex(1)


        QMetaObject.connectSlotsByName(Dialog)
    # setupUi

    def retranslateUi(self, Dialog):
        Dialog.setWindowTitle(QCoreApplication.translate("Dialog", u"Dialog", None))
        self.label_10.setText(QCoreApplication.translate("Dialog", u"Nome Fantasia:", None))
        self.lineEdit_8.setText("")
        self.label.setText(QCoreApplication.translate("Dialog", u"Raz\u00e3o Social:", None))
        self.label_15.setText(QCoreApplication.translate("Dialog", u"Data de Abertura:", None))
        self.label_13.setText(QCoreApplication.translate("Dialog", u"CNPJ / CPF :", None))
        self.lineEdit_11.setInputMask("")
        self.lineEdit_11.setText("")
        self.radioButton.setText(QCoreApplication.translate("Dialog", u"Pessoa Fis\u00edca", None))
        self.radioButton_2.setText(QCoreApplication.translate("Dialog", u"Pessoa juridica", None))
        self.groupBox.setTitle(QCoreApplication.translate("Dialog", u"Outras Informa\u00e7\u00f5es", None))
        self.checkBox_6.setText(QCoreApplication.translate("Dialog", u"Contribuinte ?", None))
        self.checkBox_7.setText(QCoreApplication.translate("Dialog", u"Optante Pelo Simples Nacional ?", None))
        self.lineEdit_14.setInputMask("")
        self.lineEdit_14.setText("")
        self.label_17.setText(QCoreApplication.translate("Dialog", u"Ramo de Atividade :", None))
        self.lineEdit_12.setInputMask("")
        self.lineEdit_12.setText("")
        self.label_14.setText(QCoreApplication.translate("Dialog", u"Inscri\u00e7\u00e3o Estadual :", None))
        self.lineEdit_13.setInputMask("")
        self.lineEdit_13.setText("")
        self.label_16.setText(QCoreApplication.translate("Dialog", u"Inscri\u00e7\u00e3o Municipal :", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.DdPrincipais), QCoreApplication.translate("Dialog", u"Dados Principais", None))
        self.label_28.setText(QCoreApplication.translate("Dialog", u"Dados Complementares :", None))
        self.lineEdit_26.setInputMask(QCoreApplication.translate("Dialog", u"#####-###", None))
        self.lineEdit_28.setInputMask(QCoreApplication.translate("Dialog", u"(##) ####-####", None))
        self.lineEdit_28.setText(QCoreApplication.translate("Dialog", u"() ------", None))
        self.checkBox_5.setText(QCoreApplication.translate("Dialog", u"Possui WhatsApp ?", None))
        self.label_29.setText(QCoreApplication.translate("Dialog", u"N \u00ba :", None))
        self.lineEdit_29.setInputMask("")
        self.label_30.setText(QCoreApplication.translate("Dialog", u"UF :", None))
        self.label_31.setText(QCoreApplication.translate("Dialog", u"Celular:", None))
        self.label_12.setText(QCoreApplication.translate("Dialog", u"Rua :", None))
        self.label_32.setText(QCoreApplication.translate("Dialog", u"Observa\u00e7\u00e3o :", None))
        self.lineEdit_32.setInputMask(QCoreApplication.translate("Dialog", u"(##) #####-####", None))
        self.lineEdit_32.setText(QCoreApplication.translate("Dialog", u"() ------", None))
        self.label_33.setText(QCoreApplication.translate("Dialog", u"Bairro :", None))
        self.label_34.setText(QCoreApplication.translate("Dialog", u"CEP :", None))
        self.label_35.setText(QCoreApplication.translate("Dialog", u"E-mail :", None))
        self.label_36.setText(QCoreApplication.translate("Dialog", u"Telefone :", None))
        self.label_37.setText(QCoreApplication.translate("Dialog", u"Cidade:", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.DdAdicionais), QCoreApplication.translate("Dialog", u"Dados Adicionais", None))
        self.pushButton_2.setText(QCoreApplication.translate("Dialog", u"A&dicionar", None))
#if QT_CONFIG(shortcut)
        self.pushButton_2.setShortcut(QCoreApplication.translate("Dialog", u"Alt+D", None))
#endif // QT_CONFIG(shortcut)
        self.pushButton_3.setText(QCoreApplication.translate("Dialog", u"&Alterar", None))
        self.pushButton_4.setText(QCoreApplication.translate("Dialog", u"&Cancelar", None))
#if QT_CONFIG(shortcut)
        self.pushButton_4.setShortcut(QCoreApplication.translate("Dialog", u"Alt+C", None))
#endif // QT_CONFIG(shortcut)
        self.pushButton_5.setText(QCoreApplication.translate("Dialog", u"&Salvar", None))
#if QT_CONFIG(shortcut)
        self.pushButton_5.setShortcut("")
#endif // QT_CONFIG(shortcut)
    # retranslateUi

