# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'CadUser.ui'
##
## Created by: Qt User Interface Compiler version 6.7.2
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QBrush, QColor, QConicalGradient, QCursor,
    QFont, QFontDatabase, QGradient, QIcon,
    QImage, QKeySequence, QLinearGradient, QPainter,
    QPalette, QPixmap, QRadialGradient, QTransform)
from PySide6.QtWidgets import (QAbstractSpinBox, QApplication, QCheckBox, QDateEdit,
    QDialog, QGroupBox, QLCDNumber, QLabel,
    QLineEdit, QPlainTextEdit, QPushButton, QSizePolicy,
    QTabWidget, QWidget)

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        if not Dialog.objectName():
            Dialog.setObjectName(u"Dialog")
        Dialog.resize(762, 611)
        self.tabWidget = QTabWidget(Dialog)
        self.tabWidget.setObjectName(u"tabWidget")
        self.tabWidget.setGeometry(QRect(0, 0, 761, 541))
        font = QFont()
        font.setFamilies([u"Segoe UI"])
        font.setPointSize(12)
        self.tabWidget.setFont(font)
        self.tabWidget.setCursor(QCursor(Qt.CursorShape.PointingHandCursor))
        self.tabWidget.setContextMenuPolicy(Qt.DefaultContextMenu)
        self.tabWidget.setAcceptDrops(False)
        self.tabWidget.setStyleSheet(u"font: 12pt \"Segoe UI\";")
        self.DdPrincipais = QWidget()
        self.DdPrincipais.setObjectName(u"DdPrincipais")
        self.label = QLabel(self.DdPrincipais)
        self.label.setObjectName(u"label")
        self.label.setGeometry(QRect(20, 50, 131, 16))
        self.lineEdit = QLineEdit(self.DdPrincipais)
        self.lineEdit.setObjectName(u"lineEdit")
        self.lineEdit.setGeometry(QRect(20, 70, 591, 21))
        self.label_2 = QLabel(self.DdPrincipais)
        self.label_2.setObjectName(u"label_2")
        self.label_2.setGeometry(QRect(20, 100, 131, 16))
        self.lineEdit_2 = QLineEdit(self.DdPrincipais)
        self.lineEdit_2.setObjectName(u"lineEdit_2")
        self.lineEdit_2.setGeometry(QRect(20, 120, 591, 21))
        self.label_3 = QLabel(self.DdPrincipais)
        self.label_3.setObjectName(u"label_3")
        self.label_3.setGeometry(QRect(20, 150, 131, 16))
        self.lineEdit_3 = QLineEdit(self.DdPrincipais)
        self.lineEdit_3.setObjectName(u"lineEdit_3")
        self.lineEdit_3.setGeometry(QRect(20, 170, 181, 21))
        self.lineEdit_3.setMaxLength(15)
        self.lineEdit_3.setCursorMoveStyle(Qt.VisualMoveStyle)
        self.label_4 = QLabel(self.DdPrincipais)
        self.label_4.setObjectName(u"label_4")
        self.label_4.setGeometry(QRect(220, 150, 151, 16))
        self.dateEdit = QDateEdit(self.DdPrincipais)
        self.dateEdit.setObjectName(u"dateEdit")
        self.dateEdit.setGeometry(QRect(220, 170, 151, 22))
        self.dateEdit.setWrapping(True)
        self.dateEdit.setSpecialValueText(u"")
        self.dateEdit.setCorrectionMode(QAbstractSpinBox.CorrectToNearestValue)
        self.dateEdit.setKeyboardTracking(False)
        self.dateEdit.setProperty("showGroupSeparator", True)
        self.dateEdit.setCalendarPopup(True)
        self.groupBox = QGroupBox(self.DdPrincipais)
        self.groupBox.setObjectName(u"groupBox")
        self.groupBox.setGeometry(QRect(10, 210, 341, 281))
        self.lineEdit_4 = QLineEdit(self.groupBox)
        self.lineEdit_4.setObjectName(u"lineEdit_4")
        self.lineEdit_4.setGeometry(QRect(10, 100, 251, 21))
        self.lineEdit_4.setEchoMode(QLineEdit.PasswordEchoOnEdit)
        self.lineEdit_4.setDragEnabled(False)
        self.lineEdit_4.setReadOnly(False)
        self.label_5 = QLabel(self.groupBox)
        self.label_5.setObjectName(u"label_5")
        self.label_5.setGeometry(QRect(10, 30, 131, 16))
        self.lineEdit_5 = QLineEdit(self.groupBox)
        self.lineEdit_5.setObjectName(u"lineEdit_5")
        self.lineEdit_5.setGeometry(QRect(10, 50, 251, 21))
        self.label_6 = QLabel(self.groupBox)
        self.label_6.setObjectName(u"label_6")
        self.label_6.setGeometry(QRect(10, 80, 131, 16))
        self.groupBox_2 = QGroupBox(self.DdPrincipais)
        self.groupBox_2.setObjectName(u"groupBox_2")
        self.groupBox_2.setGeometry(QRect(360, 210, 331, 281))
        self.checkBox = QCheckBox(self.groupBox_2)
        self.checkBox.setObjectName(u"checkBox")
        self.checkBox.setGeometry(QRect(10, 40, 301, 17))
        self.checkBox_2 = QCheckBox(self.groupBox_2)
        self.checkBox_2.setObjectName(u"checkBox_2")
        self.checkBox_2.setGeometry(QRect(10, 60, 301, 17))
        self.checkBox_2.setChecked(True)
        self.checkBox_3 = QCheckBox(self.groupBox_2)
        self.checkBox_3.setObjectName(u"checkBox_3")
        self.checkBox_3.setGeometry(QRect(10, 80, 301, 17))
        self.label_7 = QLabel(self.groupBox_2)
        self.label_7.setObjectName(u"label_7")
        self.label_7.setGeometry(QRect(10, 110, 131, 16))
        self.plainTextEdit = QPlainTextEdit(self.groupBox_2)
        self.plainTextEdit.setObjectName(u"plainTextEdit")
        self.plainTextEdit.setGeometry(QRect(10, 130, 311, 141))
        self.lcdNumber = QLCDNumber(self.DdPrincipais)
        self.lcdNumber.setObjectName(u"lcdNumber")
        self.lcdNumber.setGeometry(QRect(20, 10, 91, 23))
        self.tabWidget.addTab(self.DdPrincipais, "")
        self.DdAdicionais = QWidget()
        self.DdAdicionais.setObjectName(u"DdAdicionais")
        self.tabWidget.addTab(self.DdAdicionais, "")
        self.Permission = QWidget()
        self.Permission.setObjectName(u"Permission")
        self.tabWidget.addTab(self.Permission, "")
        self.pushButton_3 = QPushButton(Dialog)
        self.pushButton_3.setObjectName(u"pushButton_3")
        self.pushButton_3.setGeometry(QRect(610, 560, 131, 41))
        self.pushButton_3.setCheckable(False)
        self.pushButton_3.setChecked(False)
        self.pushButton_3.setAutoRepeat(False)
        self.pushButton_2 = QPushButton(Dialog)
        self.pushButton_2.setObjectName(u"pushButton_2")
        self.pushButton_2.setEnabled(True)
        self.pushButton_2.setGeometry(QRect(470, 560, 131, 41))
        self.pushButton = QPushButton(Dialog)
        self.pushButton.setObjectName(u"pushButton")
        self.pushButton.setGeometry(QRect(20, 560, 131, 41))
        self.pushButton_4 = QPushButton(Dialog)
        self.pushButton_4.setObjectName(u"pushButton_4")
        self.pushButton_4.setEnabled(False)
        self.pushButton_4.setGeometry(QRect(330, 560, 131, 41))

        self.retranslateUi(Dialog)

        self.tabWidget.setCurrentIndex(0)


        QMetaObject.connectSlotsByName(Dialog)
    # setupUi

    def retranslateUi(self, Dialog):
        Dialog.setWindowTitle(QCoreApplication.translate("Dialog", u"Dialog", None))
        self.label.setText(QCoreApplication.translate("Dialog", u"Nome Completo:", None))
        self.lineEdit.setInputMask("")
        self.label_2.setText(QCoreApplication.translate("Dialog", u"E-mail :", None))
        self.lineEdit_2.setInputMask("")
        self.label_3.setText(QCoreApplication.translate("Dialog", u"Telefone :", None))
        self.lineEdit_3.setInputMask(QCoreApplication.translate("Dialog", u"(##) #####-####", None))
        self.lineEdit_3.setText(QCoreApplication.translate("Dialog", u"() ---", None))
        self.label_4.setText(QCoreApplication.translate("Dialog", u"Data de Nascimento:", None))
        self.groupBox.setTitle(QCoreApplication.translate("Dialog", u"Configura\u00e7\u00f5es de usu\u00e1rio", None))
        self.lineEdit_4.setInputMask("")
        self.lineEdit_4.setText("")
        self.label_5.setText(QCoreApplication.translate("Dialog", u"Usu\u00e1rio :", None))
        self.lineEdit_5.setInputMask("")
        self.lineEdit_5.setText("")
        self.label_6.setText(QCoreApplication.translate("Dialog", u"Senha :", None))
        self.groupBox_2.setTitle(QCoreApplication.translate("Dialog", u"Op\u00e7\u00f5es de Usu\u00e1rio :", None))
        self.checkBox.setText(QCoreApplication.translate("Dialog", u"Resetar Senha", None))
        self.checkBox_2.setText(QCoreApplication.translate("Dialog", u"Primeiro Acesso", None))
        self.checkBox_3.setText(QCoreApplication.translate("Dialog", u"Bloqueado", None))
        self.label_7.setText(QCoreApplication.translate("Dialog", u"Observa\u00e7\u00f5es:", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.DdPrincipais), QCoreApplication.translate("Dialog", u"Dados Principais", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.DdAdicionais), QCoreApplication.translate("Dialog", u"Dados Adicionais", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.Permission), QCoreApplication.translate("Dialog", u"Permiss\u00f5es", None))
        self.pushButton_3.setText(QCoreApplication.translate("Dialog", u"&Cancelar", None))
#if QT_CONFIG(shortcut)
        self.pushButton_3.setShortcut(QCoreApplication.translate("Dialog", u"Alt+C", None))
#endif // QT_CONFIG(shortcut)
        self.pushButton_2.setText(QCoreApplication.translate("Dialog", u"A&dicionar", None))
#if QT_CONFIG(shortcut)
        self.pushButton_2.setShortcut(QCoreApplication.translate("Dialog", u"Alt+D", None))
#endif // QT_CONFIG(shortcut)
        self.pushButton.setText(QCoreApplication.translate("Dialog", u"&Alterar", None))
        self.pushButton_4.setText(QCoreApplication.translate("Dialog", u"&Salvar", None))
#if QT_CONFIG(shortcut)
        self.pushButton_4.setShortcut("")
#endif // QT_CONFIG(shortcut)
    # retranslateUi

