# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\MainLogin.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainLogin(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(350, 448)
        MainWindow.setMinimumSize(QtCore.QSize(350, 448))
        MainWindow.setMaximumSize(QtCore.QSize(350, 448))
        MainWindow.setAutoFillBackground(False)
        MainWindow.setStyleSheet(" border-top: none;")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setAutoFillBackground(True)
        self.centralwidget.setStyleSheet("alternate-background-color: rgb(28, 28, 28);")
        self.centralwidget.setObjectName("centralwidget")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(0, 0, 350, 448))
        self.frame.setAutoFillBackground(True)
        self.frame.setStyleSheet("background-color: rgb(28, 28, 28);\n"
"")
        self.frame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.lineEdit = QtWidgets.QLineEdit(self.frame)
        self.lineEdit.setGeometry(QtCore.QRect(10, 180, 331, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lineEdit.setFont(font)
        self.lineEdit.setStyleSheet("border: 1px solid #2980b9; /* Borda ao redor do frame */\n"
"selection-background-color: rgb(28, 28, 28);\n"
"border-radius: 0px; /* Arredondamento se desejar */;\n"
"border-top: none;\n"
"border-right: none;\n"
"border-left: none;\n"
"background-color: rgb(28, 28, 28);\n"
"color: rgb(255, 255, 255);")
        self.lineEdit.setText("")
        self.lineEdit.setObjectName("lineEdit")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.frame)
        self.lineEdit_2.setGeometry(QtCore.QRect(10, 260, 331, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lineEdit_2.setFont(font)
        self.lineEdit_2.setStyleSheet("border: 1px solid #2980b9; /* Borda ao redor do frame */\n"
"selection-background-color: rgb(28, 28, 28);\n"
"border-radius: 0px; /* Arredondamento se desejar */;\n"
"border-top: none;\n"
"border-right: none;\n"
"border-left: none;\n"
"background-color: rgb(28, 28, 28);\n"
"color: rgb(255, 255, 255);")
        self.lineEdit_2.setText("")
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setGeometry(QtCore.QRect(10, 150, 71, 16))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setStyleSheet("color: rgb(255, 255, 255);")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.frame)
        self.label_2.setGeometry(QtCore.QRect(10, 230, 71, 16))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_2.setObjectName("label_2")
        self.pushButton = QtWidgets.QPushButton(self.frame)
        self.pushButton.setGeometry(QtCore.QRect(60, 300, 221, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        self.pushButton.setFont(font)
        self.pushButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton.setToolTipDuration(3)
        self.pushButton.setStyleSheet("background-color: rgb(0, 0, 255);\n"
"border-radius: 10px;\n"
"color: rgb(255, 255, 255);\n"
"border: 2px;\n"
"\n"
"selection-background-color: rgb(0, 0, 212);")
        self.pushButton.setAutoDefault(False)
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(self.frame)
        self.pushButton_2.setGeometry(QtCore.QRect(70, 350, 201, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        font.setStyleStrategy(QtGui.QFont.PreferAntialias)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_2.setStyleSheet("background-color: rgb(28, 28, 28);\n"
"/*\n"
"border: 1px solid #2980b9;\n"
"border-radius: 10px;\n"
"border-top:  none;\n"
"border-left: none;\n"
"border-right: none;\n"
"border-bottom: 2px;\n"
"*/\n"
"\n"
"border: 1px solid #2980b9; /* Borda ao redor do frame */\n"
"selection-background-color: rgb(28, 28, 28);\n"
"border-radius: 0px; /* Arredondamento se desejar */;\n"
"border-top: none;\n"
"border-right: none;\n"
"border-left: none;\n"
"\n"
"color: rgb(255, 255, 255);\n"
"")
        self.pushButton_2.setObjectName("pushButton_2")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Usuário:"))
        self.label_2.setText(_translate("MainWindow", "Senha:"))
        self.pushButton.setToolTip(_translate("MainWindow", "<html><head/><body><p>Acessar o sistema.</p></body></html>"))
        self.pushButton.setText(_translate("MainWindow", "Entrar"))
        self.pushButton_2.setText(_translate("MainWindow", "Esqueci senha"))
